/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/camera/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["retry_camera"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/camera/screenshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["screenshot"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/commands/control": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["control_command"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/commands/reload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["reload_commands"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/devices/cameras": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_cameras"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/devices/serial-ports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_serial_ports"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dynamic-config/control": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["control_dynamic_config"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["test_notification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profiles/generate-launcher": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["generate_launcher"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/script-ui/action": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["script_ui_action"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/serial/control": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["control_serial"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_settings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["patch_settings"];
        trace?: never;
    };
    "/api/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_state"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/update/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["check_update"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ws": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["websocket"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiError: {
            code: components["schemas"]["ApiErrorCode"];
            message: string;
            fields: {
                [key: string]: string[];
            } | null;
        };
        /**
         * @description Closed, stable machine-readable failure codes shared by every public HTTP
         *     response. Endpoint response declarations constrain which subset is
         *     applicable, while the runtime wire type cannot emit an unregistered code.
         * @enum {string}
         */
        ApiErrorCode: "request_forbidden" | "unsupported_media_type" | "payload_too_large" | "malformed_json" | "invalid_request" | "resource_not_found" | "method_not_allowed" | "revision_conflict" | "command_not_found" | "command_state_conflict" | "profile_switch_conflict" | "serial_connection_failed" | "camera_unavailable" | "screenshot_unavailable" | "destination_conflict" | "notification_unsupported" | "dynamic_config_unavailable" | "unsupported_platform" | "persistence_failed" | "backend_unavailable" | "internal_error";
        ButtonState: {
            a: boolean;
            b: boolean;
            x: boolean;
            y: boolean;
            l: boolean;
            r: boolean;
            zl: boolean;
            zr: boolean;
            lclick: boolean;
            rclick: boolean;
            plus: boolean;
            minus: boolean;
            home: boolean;
            capture: boolean;
        };
        CameraDevice: {
            selector: components["schemas"]["CameraSelector"];
            label: string;
            available: boolean;
        };
        CameraSelector: number | string;
        /** @description Client-to-server WebSocket/DataChannel union. */
        ClientMessage: (components["schemas"]["MessageData_SessionDescription"] & {
            /** @enum {string} */
            type: "webrtc.offer";
        }) | (components["schemas"]["MessageData_SessionDescription"] & {
            /** @enum {string} */
            type: "webrtc.answer";
        }) | (components["schemas"]["MessageData_IceCandidate"] & {
            /** @enum {string} */
            type: "webrtc.ice_candidate";
        }) | (components["schemas"]["MessageData_InputSnapshot"] & {
            /** @enum {string} */
            type: "input.snapshot";
        }) | (components["schemas"]["MessageData_KeyboardInput"] & {
            /** @enum {string} */
            type: "keyboard_input";
        }) | (components["schemas"]["MessageData_MouseStickInput"] & {
            /** @enum {string} */
            type: "mouse_stick_input";
        }) | (components["schemas"]["MessageData_MouseInput"] & {
            /** @enum {string} */
            type: "mouse_input";
        }) | (components["schemas"]["MessageData_GamepadInput"] & {
            /** @enum {string} */
            type: "gamepad_input";
        }) | (components["schemas"]["MessageData_Nonce"] & {
            /** @enum {string} */
            type: "pong";
        });
        CommandControlRequest: (components["schemas"]["CommandStartFields"] & {
            /** @enum {string} */
            action: "start";
        }) | {
            /** @enum {string} */
            action: "stop";
        } | {
            /** @enum {string} */
            action: "pause";
        } | {
            /** @enum {string} */
            action: "resume";
        };
        CommandDisplayCommand: {
            command: components["schemas"]["CommandInfo"];
        };
        CommandDisplayItem: (components["schemas"]["CommandDisplayCommand"] & {
            /** @enum {string} */
            kind: "command";
        }) | (components["schemas"]["CommandDisplaySeparator"] & {
            /** @enum {string} */
            kind: "separator";
        });
        CommandDisplaySeparator: {
            label: string | null;
        };
        CommandIdentity: {
            module_path: string;
            class_name: string;
        };
        CommandInfo: {
            name: string;
            module_path: string;
            class_name: string;
            tags: string[];
        };
        CommandStartFields: {
            command: components["schemas"]["CommandIdentity"];
        };
        /** @enum {string} */
        CommandState: "running" | "paused" | "stopped" | "error";
        /**
         * @description An exact non-negative integer wire value that never depends on JavaScript
         *     `Number` precision.
         * @example 42
         */
        DecimalString: string;
        DynamicConfigControlRequest: (components["schemas"]["DynamicLoadPath"] & {
            /** @enum {string} */
            action: "load_path";
        }) | (components["schemas"]["DynamicLoadContent"] & {
            /** @enum {string} */
            action: "load_content";
        }) | {
            /** @enum {string} */
            action: "reload";
        };
        DynamicConfigResult: {
            display_path: string;
            language: components["schemas"]["DynamicLanguage"];
            loaded: boolean;
        };
        /** @enum {string} */
        DynamicLanguage: "python" | "lua";
        DynamicLoadContent: {
            language: components["schemas"]["DynamicLanguage"];
            content: string;
        };
        DynamicLoadPath: {
            path: string;
        };
        EmptyRequest: Record<string, never>;
        /** @description Common secret-safe error envelope. */
        ErrorEnvelope: {
            error: components["schemas"]["ApiError"];
        };
        /** @enum {string} */
        GamepadButton: "A" | "B" | "X" | "Y" | "L" | "R" | "ZL" | "ZR" | "LCLICK" | "RCLICK" | "MINUS" | "PLUS" | "HOME" | "CAPTURE";
        GamepadButtonInput: {
            generation: string;
            sequence: components["schemas"]["DecimalString"];
            button: components["schemas"]["GamepadButton"];
            state: components["schemas"]["PressState"];
        };
        /** @enum {string} */
        GamepadHat: "UP" | "DOWN" | "LEFT" | "RIGHT" | "TOP_RIGHT" | "BTM_RIGHT" | "BTM_LEFT" | "TOP_LEFT" | "CENTER";
        GamepadHatInput: {
            generation: string;
            sequence: components["schemas"]["DecimalString"];
            hat: components["schemas"]["GamepadHat"];
        };
        GamepadInput: (components["schemas"]["GamepadButtonInput"] & {
            /** @enum {string} */
            kind: "button";
        }) | (components["schemas"]["GamepadStickInput"] & {
            /** @enum {string} */
            kind: "stick";
        }) | (components["schemas"]["GamepadHatInput"] & {
            /** @enum {string} */
            kind: "hat";
        }) | (components["schemas"]["GamepadTouchInput"] & {
            /** @enum {string} */
            kind: "touch";
        });
        GamepadStickInput: {
            generation: string;
            sequence: components["schemas"]["DecimalString"];
            stick: components["schemas"]["StickName"];
            /** Format: int32 */
            x: number;
            /** Format: int32 */
            y: number;
        };
        GamepadTouchInput: {
            generation: string;
            sequence: components["schemas"]["DecimalString"];
            touch: null | components["schemas"]["TouchPoint"];
        };
        GenerateLauncherRequest: {
            profile: string;
            copy_current: boolean;
            destination: components["schemas"]["LauncherDestination"];
        };
        GenerateLauncherResult: {
            profile_created: boolean;
            launcher_created: boolean;
            revision: components["schemas"]["DecimalString"];
        };
        /** @enum {string} */
        Hat: "up" | "down" | "left" | "right" | "up_right" | "up_left" | "down_right" | "down_left" | "neutral";
        IceCandidate: {
            candidate: string;
            negotiation_id?: string | null;
            sdp_mid: string | null;
            /** Format: int32 */
            sdp_mline_index: number | null;
            username_fragment: string | null;
        };
        /** @enum {string} */
        ImageFormat: "png" | "jpeg";
        InputApplied: {
            generation: string;
            sequence: components["schemas"]["DecimalString"];
        };
        InputGeneration: {
            generation: string;
        };
        InputSnapshot: {
            generation: string;
            /** @enum {string} */
            sequence: "0";
            keyboard_keys: string[];
            mouse_buttons: components["schemas"]["MouseButtons"];
            buttons: components["schemas"]["ButtonState"];
            hat: components["schemas"]["Hat"];
            left_stick: components["schemas"]["StickPosition"];
            right_stick: components["schemas"]["StickPosition"];
            touch: null | components["schemas"]["TouchPoint"];
        };
        KeyboardInput: {
            generation: string;
            sequence: components["schemas"]["DecimalString"];
            key: string;
            state: components["schemas"]["PressState"];
        };
        LauncherDestination: (components["schemas"]["LauncherPath"] & {
            /** @enum {string} */
            kind: "path";
        }) | (components["schemas"]["LauncherDownload"] & {
            /** @enum {string} */
            kind: "download";
        });
        LauncherDownload: {
            filename: string | null;
        };
        LauncherPath: {
            path: string;
        };
        LogData: {
            level: components["schemas"]["LogLevel"];
            message: string;
            target: components["schemas"]["LogTarget"];
            operation: components["schemas"]["LogOperation"];
        };
        /** @enum {string} */
        LogLevel: "debug" | "info" | "warning" | "error" | "critical";
        /**
         * @description Mutation semantics for one output-panel message. Ordinary diagnostics
         *     append, while the compatibility print APIs may replace or clear a panel.
         * @enum {string}
         */
        LogOperation: "append" | "replace" | "clear";
        /** @enum {string} */
        LogTarget: "stdout" | "panel1" | "panel2" | "log";
        MessageData_GamepadInput: {
            data: (components["schemas"]["GamepadButtonInput"] & {
                /** @enum {string} */
                kind: "button";
            }) | (components["schemas"]["GamepadStickInput"] & {
                /** @enum {string} */
                kind: "stick";
            }) | (components["schemas"]["GamepadHatInput"] & {
                /** @enum {string} */
                kind: "hat";
            }) | (components["schemas"]["GamepadTouchInput"] & {
                /** @enum {string} */
                kind: "touch";
            });
        };
        MessageData_IceCandidate: {
            data: {
                candidate: string;
                negotiation_id?: string | null;
                sdp_mid: string | null;
                /** Format: int32 */
                sdp_mline_index: number | null;
                username_fragment: string | null;
            };
        };
        MessageData_InputApplied: {
            data: {
                generation: string;
                sequence: components["schemas"]["DecimalString"];
            };
        };
        MessageData_InputGeneration: {
            data: {
                generation: string;
            };
        };
        MessageData_InputSnapshot: {
            data: {
                generation: string;
                /** @enum {string} */
                sequence: "0";
                keyboard_keys: string[];
                mouse_buttons: components["schemas"]["MouseButtons"];
                buttons: components["schemas"]["ButtonState"];
                hat: components["schemas"]["Hat"];
                left_stick: components["schemas"]["StickPosition"];
                right_stick: components["schemas"]["StickPosition"];
                touch: null | components["schemas"]["TouchPoint"];
            };
        };
        MessageData_KeyboardInput: {
            data: {
                generation: string;
                sequence: components["schemas"]["DecimalString"];
                key: string;
                state: components["schemas"]["PressState"];
            };
        };
        MessageData_LogData: {
            data: {
                level: components["schemas"]["LogLevel"];
                message: string;
                target: components["schemas"]["LogTarget"];
                operation: components["schemas"]["LogOperation"];
            };
        };
        MessageData_MouseInput: {
            data: {
                generation: string;
                sequence: components["schemas"]["DecimalString"];
                button: components["schemas"]["MouseButton"];
                state: components["schemas"]["PressState"];
                /** Format: int32 */
                x: number;
                /** Format: int32 */
                y: number;
            };
        };
        MessageData_MouseStickInput: {
            data: {
                generation: string;
                sequence: components["schemas"]["DecimalString"];
                stick: components["schemas"]["StickName"];
                /** Format: int32 */
                x: number;
                /** Format: int32 */
                y: number;
            };
        };
        MessageData_Nonce: {
            data: {
                nonce: string;
            };
        };
        MessageData_ScriptUiSnapshot: {
            /**
             * @description Latest complete profile-scoped script UI state. The broker replays this
             *     snapshot to every newly connected client, so browser reconnects never need
             *     to infer missed dialog or Tk mutations.
             */
            data: {
                generation: string | null;
                dialogs: components["schemas"]["ScriptDialog"][];
                tk_windows: components["schemas"]["ScriptTkWindow"][];
                overlay: components["schemas"]["ScriptOverlaySnapshot"];
                popup_images: components["schemas"]["ScriptPopupImage"][];
            };
        };
        MessageData_SerialData: {
            data: {
                encoding: components["schemas"]["SerialEncoding"];
                data: string;
                byte_length: number;
            };
        };
        MessageData_SessionDescription: {
            data: {
                sdp: string;
                negotiation_id?: string | null;
            };
        };
        /** @enum {string} */
        MouseButton: "left" | "right" | "middle";
        MouseButtons: {
            left: boolean;
            right: boolean;
            middle: boolean;
        };
        MouseInput: {
            generation: string;
            sequence: components["schemas"]["DecimalString"];
            button: components["schemas"]["MouseButton"];
            state: components["schemas"]["PressState"];
            /** Format: int32 */
            x: number;
            /** Format: int32 */
            y: number;
        };
        MouseStickInput: {
            generation: string;
            sequence: components["schemas"]["DecimalString"];
            stick: components["schemas"]["StickName"];
            /** Format: int32 */
            x: number;
            /** Format: int32 */
            y: number;
        };
        Nonce: {
            nonce: string;
        };
        NormalizedRegion: {
            /** Format: double */
            x: number;
            /** Format: double */
            y: number;
            /** Format: double */
            width: number;
            /** Format: double */
            height: number;
        };
        NotificationTestRequest: {
            /** @enum {string} */
            channel: "windows";
        } | {
            /** @enum {string} */
            channel: "discord";
        };
        NotificationTestResult: {
            delivered: boolean;
        };
        OperationResult: {
            changed: boolean;
            revision: components["schemas"]["DecimalString"];
        };
        /** @enum {string} */
        PressState: "pressed" | "released";
        RevisionedStateChange: {
            revision: components["schemas"]["DecimalString"];
            data: components["schemas"]["UiStateChange"];
        };
        SavedScreenshot: {
            display_path: string;
            format: components["schemas"]["ImageFormat"];
        };
        ScreenshotCaptures: {
            region?: null | components["schemas"]["NormalizedRegion"];
            filename?: string | null;
            format?: null | components["schemas"]["ImageFormat"];
            overwrite?: boolean;
        };
        ScreenshotDownload: {
            region?: null | components["schemas"]["NormalizedRegion"];
            filename?: string | null;
            format: components["schemas"]["ImageFormat"];
        };
        ScreenshotPath: {
            region?: null | components["schemas"]["NormalizedRegion"];
            path: string;
            format: components["schemas"]["ImageFormat"];
            overwrite?: boolean;
        };
        ScreenshotRequest: (components["schemas"]["ScreenshotCaptures"] & {
            /** @enum {string} */
            destination: "captures";
        }) | (components["schemas"]["ScreenshotPath"] & {
            /** @enum {string} */
            destination: "path";
        }) | (components["schemas"]["ScreenshotDownload"] & {
            /** @enum {string} */
            destination: "download";
        });
        ScriptDialog: {
            id: components["schemas"]["DecimalString"];
            title: string;
            description: string | null;
            widgets: components["schemas"]["ScriptDialogWidget"][];
        };
        /** @enum {string} */
        ScriptDialogAbortReason: "close" | "escape" | "destroy";
        /** @description Script-dialog value kept type-safe across Python, Rust, and the browser. */
        ScriptDialogValue: {
            /** @enum {string} */
            type: "none";
        } | {
            value: string;
            /** @enum {string} */
            type: "string";
        } | {
            value: boolean;
            /** @enum {string} */
            type: "bool";
        } | {
            /** Format: int64 */
            value: number;
            /** @enum {string} */
            type: "integer";
        } | {
            /** Format: double */
            value: number;
            /** @enum {string} */
            type: "float";
        };
        ScriptDialogWidget: {
            kind: components["schemas"]["ScriptDialogWidgetKind"];
            label: string | null;
            value: components["schemas"]["ScriptDialogValue"];
            options: components["schemas"]["ScriptDialogValue"][];
            /** Format: double */
            minimum: number | null;
            /** Format: double */
            maximum: number | null;
            /** Format: int32 */
            precision: number | null;
        };
        /** @enum {string} */
        ScriptDialogWidgetKind: "entry" | "check" | "combo" | "radio" | "spin" | "scale" | "next";
        ScriptOverlayRectangle: {
            tag: string;
            /** Format: int64 */
            x1: number;
            /** Format: int64 */
            y1: number;
            /** Format: int64 */
            x2: number;
            /** Format: int64 */
            y2: number;
            outline: string;
        };
        ScriptOverlayShape: (components["schemas"]["ScriptOverlayRectangle"] & {
            /** @enum {string} */
            kind: "rectangle";
        }) | (components["schemas"]["ScriptOverlayText"] & {
            /** @enum {string} */
            kind: "text";
        });
        ScriptOverlaySnapshot: {
            /** Format: int32 */
            fps: number;
            /** Format: int32 */
            show_width: number;
            /** Format: int32 */
            show_height: number;
            right_mouse_mode: string;
            touchscreen_area: components["schemas"]["NormalizedRegion"];
            bindings: components["schemas"]["ScriptPointerBindings"];
            shapes: components["schemas"]["ScriptOverlayShape"][];
        };
        ScriptOverlayText: {
            tag: string;
            /** Format: int64 */
            x: number;
            /** Format: int64 */
            y: number;
            text: string;
            font: string;
            /** Format: int32 */
            font_size: number;
            color: string;
        };
        ScriptPointerBindings: {
            left: boolean;
            right: boolean;
        };
        /** @enum {string} */
        ScriptPointerButton: "left" | "right";
        /** @enum {string} */
        ScriptPointerPhase: "pressed" | "moved" | "released";
        ScriptPopupImage: {
            id: components["schemas"]["DecimalString"];
            title: string;
            content_type: string;
            encoded_base64: string;
        };
        ScriptTkButton: {
            id: components["schemas"]["DecimalString"];
            text: string;
            /** Format: int64 */
            pady: number | null;
        };
        ScriptTkLabel: {
            id: components["schemas"]["DecimalString"];
            text: string;
            /** Format: int64 */
            width: number | null;
            /** Format: int64 */
            height: number | null;
            relief: string | null;
            background: string | null;
            /** Format: int64 */
            pady: number | null;
        };
        ScriptTkScale: {
            id: components["schemas"]["DecimalString"];
            /** Format: double */
            from_value: number;
            /** Format: double */
            to_value: number;
            orient: string;
            label: string | null;
            /** Format: double */
            value: number;
            /** Format: int64 */
            pady: number | null;
        };
        ScriptTkWidget: (components["schemas"]["ScriptTkScale"] & {
            /** @enum {string} */
            kind: "scale";
        }) | (components["schemas"]["ScriptTkButton"] & {
            /** @enum {string} */
            kind: "button";
        }) | (components["schemas"]["ScriptTkLabel"] & {
            /** @enum {string} */
            kind: "label";
        });
        ScriptTkWindow: {
            id: components["schemas"]["DecimalString"];
            title: string;
            geometry: string | null;
            widgets: components["schemas"]["ScriptTkWidget"][];
        };
        /** @description Browser-originated, generation-checked interaction with script-owned UI. */
        ScriptUiAction: {
            generation: string;
            dialog_id: components["schemas"]["DecimalString"];
            values: components["schemas"]["ScriptDialogValue"][];
            /** @enum {string} */
            action: "dialog_confirm";
        } | {
            generation: string;
            dialog_id: components["schemas"]["DecimalString"];
            reason: components["schemas"]["ScriptDialogAbortReason"];
            /** @enum {string} */
            action: "dialog_abort";
        } | {
            generation: string;
            widget_id: components["schemas"]["DecimalString"];
            /** Format: double */
            value: number;
            /** @enum {string} */
            action: "tk_scale_changed";
        } | {
            generation: string;
            widget_id: components["schemas"]["DecimalString"];
            /** @enum {string} */
            action: "tk_button_invoked";
        } | {
            generation: string;
            window_id: components["schemas"]["DecimalString"];
            /** @enum {string} */
            action: "tk_window_closed";
        } | {
            generation: string;
            popup_id: components["schemas"]["DecimalString"];
            /** @enum {string} */
            action: "popup_closed";
        } | {
            generation: string;
            button: components["schemas"]["ScriptPointerButton"];
            phase: components["schemas"]["ScriptPointerPhase"];
            /** Format: int32 */
            x: number;
            /** Format: int32 */
            y: number;
            /** @enum {string} */
            action: "pointer";
        };
        ScriptUiActionResult: {
            accepted: boolean;
        };
        /**
         * @description Latest complete profile-scoped script UI state. The broker replays this
         *     snapshot to every newly connected client, so browser reconnects never need
         *     to infer missed dialog or Tk mutations.
         */
        ScriptUiSnapshot: {
            generation: string | null;
            dialogs: components["schemas"]["ScriptDialog"][];
            tk_windows: components["schemas"]["ScriptTkWindow"][];
            overlay: components["schemas"]["ScriptOverlaySnapshot"];
            popup_images: components["schemas"]["ScriptPopupImage"][];
        };
        SerialControlRequest: {
            /** @enum {string} */
            action: "connect";
        } | {
            /** @enum {string} */
            action: "disconnect";
        };
        SerialData: {
            encoding: components["schemas"]["SerialEncoding"];
            data: string;
            byte_length: number;
        };
        /** @enum {string} */
        SerialEncoding: "base64";
        SerialPort: {
            selector: string;
            label: string;
            available: boolean;
        };
        /**
         * @description Server-to-client WebSocket union. Every JSON variant is closed and only
         *     state changes carry a revision.
         */
        ServerMessage: (components["schemas"]["RevisionedStateChange"] & {
            /** @enum {string} */
            type: "ui.state.changed";
        }) | (components["schemas"]["MessageData_SerialData"] & {
            /** @enum {string} */
            type: "serial.data";
        }) | (components["schemas"]["MessageData_LogData"] & {
            /** @enum {string} */
            type: "log";
        }) | (components["schemas"]["MessageData_ScriptUiSnapshot"] & {
            /** @enum {string} */
            type: "script.ui";
        }) | (components["schemas"]["MessageData_SessionDescription"] & {
            /** @enum {string} */
            type: "webrtc.offer";
        }) | (components["schemas"]["MessageData_SessionDescription"] & {
            /** @enum {string} */
            type: "webrtc.answer";
        }) | (components["schemas"]["MessageData_IceCandidate"] & {
            /** @enum {string} */
            type: "webrtc.ice_candidate";
        }) | (components["schemas"]["MessageData_InputGeneration"] & {
            /** @enum {string} */
            type: "input.generation";
        }) | (components["schemas"]["MessageData_InputApplied"] & {
            /** @enum {string} */
            type: "input.snapshot.applied";
        }) | (components["schemas"]["MessageData_Nonce"] & {
            /** @enum {string} */
            type: "ping";
        });
        SessionDescription: {
            sdp: string;
            negotiation_id?: string | null;
        };
        SettingsChange: {
            values: components["schemas"]["SettingsReadPatchValues"];
            pending_restart_values: components["schemas"]["SettingsReadPatchValues"];
            restart_required: string[];
            apply_failures: {
                [key: string]: string;
            };
        };
        SettingsPatchRequest: {
            expected_revision?: null | components["schemas"]["DecimalString"];
            values: components["schemas"]["SettingsWriteValues"];
        };
        SettingsReadPatchValues: {
            /** @enum {string} */
            language?: "ja" | "en";
            auto_reload_config?: boolean;
            /** Format: int64 */
            "dynamic.callback_soft_timeout_ms"?: number;
            /** Format: int64 */
            "dynamic.callback_soft_timeout_grace_ms"?: number;
            /** Format: int64 */
            "dynamic.callback_hard_timeout_ms"?: number;
            /** Format: int64 */
            "dynamic.callback_max_concurrency"?: number;
            /** Format: int64 */
            "dynamic.callback_queue_capacity"?: number;
            report_ignored_profile_global_settings?: boolean;
            /** Format: profile_name */
            active_profile?: string;
            /** Format: int64 */
            "camera.capture_fps"?: number;
            /** @enum {string} */
            "camera.capture_resolution"?: "640x360" | "1280x720" | "1920x1080";
            "camera.device"?: number | string;
            /** @enum {string} */
            "camera.flip_mode"?: "none" | "vertical" | "horizontal" | "both";
            /** @enum {string} */
            "camera.screenshot_format"?: "png" | "jpeg";
            /** Format: free */
            "serial.port"?: string;
            /** Format: int64 */
            "serial.baud_rate"?: number;
            /** @enum {string} */
            "serial.data_format"?: "default" | "qingpi" | "3ds";
            "input.keyboard_enabled"?: boolean;
            "input.left_stick_mouse_enabled"?: boolean;
            "input.right_stick_mouse_enabled"?: boolean;
            "input.touchscreen_area"?: {
                /** Format: double */
                bottom: number;
                /** Format: double */
                left: number;
                /** Format: double */
                right: number;
                /** Format: double */
                top: number;
            };
            "input.allow_manual_intervention"?: boolean;
            /** @enum {string} */
            "notifications.line_menu_behavior"?: "message" | "noop";
            /** @description Secret-safe status; the secret value is never returned */
            "notifications.discord.webhook_url"?: {
                configured: boolean;
            };
            /** Format: free */
            "notifications.discord.username"?: string;
            /** Format: http_url_or_empty */
            "notifications.discord.avatar_url"?: string;
            "notifications.discord.on_script_start"?: boolean;
            "notifications.discord.on_script_end"?: boolean;
            "notifications.windows.on_script_start"?: boolean;
            "notifications.windows.on_script_end"?: boolean;
            /** Format: int64 */
            "websocket.reconnect_interval_sec"?: number;
            /** Format: int64 */
            "websocket.reconnect_max_retries"?: number;
            /** Format: int64 */
            "websocket.ping_interval_sec"?: number;
            /** Format: int64 */
            "websocket.pong_timeout_sec"?: number;
            "webrtc.auto_recover"?: boolean;
            /** Format: int64 */
            "webrtc.recovery_probe_interval_sec"?: number;
            /** Format: stun_uri_or_empty */
            stun_server?: string;
            /** Format: int64 */
            jpeg_quality?: number;
            "server.web_dir"?: string;
            /** Format: int64 */
            "server.port"?: number;
            /** Format: ip_literal_non_wildcard */
            "server.bind_address"?: string;
            "ui.fps_options"?: number[];
            /** Format: int64 */
            "ui.fps"?: number;
            /** @enum {string} */
            "ui.widget_mode"?: "all" | "outputs" | "output_1_controller" | "output_2_controller" | "output_1" | "output_2" | "controller";
            /** Format: int64 */
            "ui.output_split_ratio"?: number;
            /** @enum {string} */
            "ui.stdout_destination"?: "output_1" | "output_2";
            /** @enum {string} */
            "ui.controller_position"?: "top" | "bottom";
            /** @enum {string} */
            "ui.dialog_button_position"?: "bottom" | "top" | "both";
            "ui.camera.live_view_enabled"?: boolean;
            "ui.camera.pixel_values_visible"?: boolean;
            "ui.camera.guide_visible"?: boolean;
            /** @enum {string} */
            "ui.desktop.close_behavior"?: "ask" | "shutdown" | "keep_backend";
            "ui.desktop.disable_compositing"?: boolean;
            /** Format: free */
            "shortcuts.button_1"?: string;
            /** Format: free */
            "shortcuts.button_2"?: string;
            /** Format: free */
            "shortcuts.button_3"?: string;
            /** Format: free */
            "shortcuts.button_4"?: string;
            /** Format: free */
            "shortcuts.button_5"?: string;
            /** Format: free */
            "shortcuts.button_6"?: string;
            /** Format: free */
            "shortcuts.button_7"?: string;
            /** Format: free */
            "shortcuts.button_8"?: string;
            /** Format: free */
            "shortcuts.button_9"?: string;
            /** Format: free */
            "shortcuts.button_10"?: string;
            /** @enum {string} */
            "commands.tag_match_mode"?: "exact" | "partial" | "prefix" | "suffix";
            "python.script.venv"?: string;
            /** Format: int64 */
            "python.script.shutdown_timeout_ms"?: number;
            "python.script.packages.list"?: {
                extras?: string[];
                name: string;
                version?: string;
            }[];
            "python.script.packages.override_application_constraints"?: boolean;
            "python.script.packages.override_package_metadata_constraints"?: boolean;
            "python.script.packages.uv_config"?: null | string;
            "python.script.packages.revalidate_mutable_sources"?: boolean;
        };
        SettingsReadValues: {
            /** @enum {string} */
            language: "ja" | "en";
            auto_reload_config: boolean;
            /** Format: int64 */
            "dynamic.callback_soft_timeout_ms": number;
            /** Format: int64 */
            "dynamic.callback_soft_timeout_grace_ms": number;
            /** Format: int64 */
            "dynamic.callback_hard_timeout_ms": number;
            /** Format: int64 */
            "dynamic.callback_max_concurrency": number;
            /** Format: int64 */
            "dynamic.callback_queue_capacity": number;
            report_ignored_profile_global_settings: boolean;
            /** Format: profile_name */
            active_profile: string;
            /** Format: int64 */
            "camera.capture_fps": number;
            /** @enum {string} */
            "camera.capture_resolution": "640x360" | "1280x720" | "1920x1080";
            "camera.device": number | string;
            /** @enum {string} */
            "camera.flip_mode": "none" | "vertical" | "horizontal" | "both";
            /** @enum {string} */
            "camera.screenshot_format": "png" | "jpeg";
            /** Format: free */
            "serial.port": string;
            /** Format: int64 */
            "serial.baud_rate": number;
            /** @enum {string} */
            "serial.data_format": "default" | "qingpi" | "3ds";
            "input.keyboard_enabled": boolean;
            "input.left_stick_mouse_enabled": boolean;
            "input.right_stick_mouse_enabled": boolean;
            "input.touchscreen_area": {
                /** Format: double */
                bottom: number;
                /** Format: double */
                left: number;
                /** Format: double */
                right: number;
                /** Format: double */
                top: number;
            };
            "input.allow_manual_intervention": boolean;
            /** @enum {string} */
            "notifications.line_menu_behavior": "message" | "noop";
            /** @description Secret-safe status; the secret value is never returned */
            "notifications.discord.webhook_url": {
                configured: boolean;
            };
            /** Format: free */
            "notifications.discord.username": string;
            /** Format: http_url_or_empty */
            "notifications.discord.avatar_url": string;
            "notifications.discord.on_script_start": boolean;
            "notifications.discord.on_script_end": boolean;
            "notifications.windows.on_script_start": boolean;
            "notifications.windows.on_script_end": boolean;
            /** Format: int64 */
            "websocket.reconnect_interval_sec": number;
            /** Format: int64 */
            "websocket.reconnect_max_retries": number;
            /** Format: int64 */
            "websocket.ping_interval_sec": number;
            /** Format: int64 */
            "websocket.pong_timeout_sec": number;
            "webrtc.auto_recover": boolean;
            /** Format: int64 */
            "webrtc.recovery_probe_interval_sec": number;
            /** Format: stun_uri_or_empty */
            stun_server: string;
            /** Format: int64 */
            jpeg_quality: number;
            "server.web_dir": string;
            /** Format: int64 */
            "server.port": number;
            /** Format: ip_literal_non_wildcard */
            "server.bind_address": string;
            "ui.fps_options": number[];
            /** Format: int64 */
            "ui.fps": number;
            /** @enum {string} */
            "ui.widget_mode": "all" | "outputs" | "output_1_controller" | "output_2_controller" | "output_1" | "output_2" | "controller";
            /** Format: int64 */
            "ui.output_split_ratio": number;
            /** @enum {string} */
            "ui.stdout_destination": "output_1" | "output_2";
            /** @enum {string} */
            "ui.controller_position": "top" | "bottom";
            /** @enum {string} */
            "ui.dialog_button_position": "bottom" | "top" | "both";
            "ui.camera.live_view_enabled": boolean;
            "ui.camera.pixel_values_visible": boolean;
            "ui.camera.guide_visible": boolean;
            /** @enum {string} */
            "ui.desktop.close_behavior": "ask" | "shutdown" | "keep_backend";
            "ui.desktop.disable_compositing": boolean;
            /** Format: free */
            "shortcuts.button_1": string;
            /** Format: free */
            "shortcuts.button_2": string;
            /** Format: free */
            "shortcuts.button_3": string;
            /** Format: free */
            "shortcuts.button_4": string;
            /** Format: free */
            "shortcuts.button_5": string;
            /** Format: free */
            "shortcuts.button_6": string;
            /** Format: free */
            "shortcuts.button_7": string;
            /** Format: free */
            "shortcuts.button_8": string;
            /** Format: free */
            "shortcuts.button_9": string;
            /** Format: free */
            "shortcuts.button_10": string;
            /** @enum {string} */
            "commands.tag_match_mode": "exact" | "partial" | "prefix" | "suffix";
            "python.script.venv": string;
            /** Format: int64 */
            "python.script.shutdown_timeout_ms": number;
            "python.script.packages.list": {
                extras?: string[];
                name: string;
                version?: string;
            }[];
            "python.script.packages.override_application_constraints": boolean;
            "python.script.packages.override_package_metadata_constraints": boolean;
            "python.script.packages.uv_config": null | string;
            "python.script.packages.revalidate_mutable_sources": boolean;
        };
        SettingsSnapshot: {
            /** @description Random identity shared by all snapshots from one backend process. */
            instance_id: string;
            revision: components["schemas"]["DecimalString"];
            values: components["schemas"]["SettingsReadValues"];
            pending_restart_values: components["schemas"]["SettingsReadPatchValues"];
            restart_required: string[];
            apply_failures: {
                [key: string]: string;
            };
        };
        SettingsWriteValues: {
            /** @enum {string} */
            language?: "ja" | "en";
            auto_reload_config?: boolean;
            /** Format: int64 */
            "dynamic.callback_soft_timeout_ms"?: number;
            /** Format: int64 */
            "dynamic.callback_soft_timeout_grace_ms"?: number;
            /** Format: int64 */
            "dynamic.callback_hard_timeout_ms"?: number;
            /** Format: int64 */
            "dynamic.callback_max_concurrency"?: number;
            /** Format: int64 */
            "dynamic.callback_queue_capacity"?: number;
            report_ignored_profile_global_settings?: boolean;
            /** Format: profile_name */
            active_profile?: string;
            /** Format: int64 */
            "camera.capture_fps"?: number;
            /** @enum {string} */
            "camera.capture_resolution"?: "640x360" | "1280x720" | "1920x1080";
            "camera.device"?: number | string;
            /** @enum {string} */
            "camera.flip_mode"?: "none" | "vertical" | "horizontal" | "both";
            /** @enum {string} */
            "camera.screenshot_format"?: "png" | "jpeg";
            /** Format: free */
            "serial.port"?: string;
            /** Format: int64 */
            "serial.baud_rate"?: number;
            /** @enum {string} */
            "serial.data_format"?: "default" | "qingpi" | "3ds";
            "input.keyboard_enabled"?: boolean;
            "input.left_stick_mouse_enabled"?: boolean;
            "input.right_stick_mouse_enabled"?: boolean;
            "input.touchscreen_area"?: {
                /** Format: double */
                bottom: number;
                /** Format: double */
                left: number;
                /** Format: double */
                right: number;
                /** Format: double */
                top: number;
            };
            "input.allow_manual_intervention"?: boolean;
            /** @enum {string} */
            "notifications.line_menu_behavior"?: "message" | "noop";
            /** Format: discord_webhook_or_empty */
            "notifications.discord.webhook_url"?: string;
            /** Format: free */
            "notifications.discord.username"?: string;
            /** Format: http_url_or_empty */
            "notifications.discord.avatar_url"?: string;
            "notifications.discord.on_script_start"?: boolean;
            "notifications.discord.on_script_end"?: boolean;
            "notifications.windows.on_script_start"?: boolean;
            "notifications.windows.on_script_end"?: boolean;
            /** Format: int64 */
            "websocket.reconnect_interval_sec"?: number;
            /** Format: int64 */
            "websocket.reconnect_max_retries"?: number;
            /** Format: int64 */
            "websocket.ping_interval_sec"?: number;
            /** Format: int64 */
            "websocket.pong_timeout_sec"?: number;
            "webrtc.auto_recover"?: boolean;
            /** Format: int64 */
            "webrtc.recovery_probe_interval_sec"?: number;
            /** Format: stun_uri_or_empty */
            stun_server?: string;
            /** Format: int64 */
            jpeg_quality?: number;
            "server.web_dir"?: string;
            /** Format: int64 */
            "server.port"?: number;
            /** Format: ip_literal_non_wildcard */
            "server.bind_address"?: string;
            "ui.fps_options"?: number[];
            /** Format: int64 */
            "ui.fps"?: number;
            /** @enum {string} */
            "ui.widget_mode"?: "all" | "outputs" | "output_1_controller" | "output_2_controller" | "output_1" | "output_2" | "controller";
            /** Format: int64 */
            "ui.output_split_ratio"?: number;
            /** @enum {string} */
            "ui.stdout_destination"?: "output_1" | "output_2";
            /** @enum {string} */
            "ui.controller_position"?: "top" | "bottom";
            /** @enum {string} */
            "ui.dialog_button_position"?: "bottom" | "top" | "both";
            "ui.camera.live_view_enabled"?: boolean;
            "ui.camera.pixel_values_visible"?: boolean;
            "ui.camera.guide_visible"?: boolean;
            /** @enum {string} */
            "ui.desktop.close_behavior"?: "ask" | "shutdown" | "keep_backend";
            "ui.desktop.disable_compositing"?: boolean;
            /** Format: free */
            "shortcuts.button_1"?: string;
            /** Format: free */
            "shortcuts.button_2"?: string;
            /** Format: free */
            "shortcuts.button_3"?: string;
            /** Format: free */
            "shortcuts.button_4"?: string;
            /** Format: free */
            "shortcuts.button_5"?: string;
            /** Format: free */
            "shortcuts.button_6"?: string;
            /** Format: free */
            "shortcuts.button_7"?: string;
            /** Format: free */
            "shortcuts.button_8"?: string;
            /** Format: free */
            "shortcuts.button_9"?: string;
            /** Format: free */
            "shortcuts.button_10"?: string;
            /** @enum {string} */
            "commands.tag_match_mode"?: "exact" | "partial" | "prefix" | "suffix";
            "python.script.venv"?: string;
            /** Format: int64 */
            "python.script.shutdown_timeout_ms"?: number;
            "python.script.packages.list"?: {
                extras?: string[];
                name: string;
                version?: string;
            }[];
            "python.script.packages.override_application_constraints"?: boolean;
            "python.script.packages.override_package_metadata_constraints"?: boolean;
            "python.script.packages.uv_config"?: null | string;
            "python.script.packages.revalidate_mutable_sources"?: boolean;
        };
        /** @enum {string} */
        StateChangeCause: "settings" | "camera" | "serial" | "command" | "profile" | "dynamic_config" | "commands" | "shutdown" | "other";
        /** @description Sparse state payload emitted by exactly one visible transaction. */
        StatePatch: {
            serial_port?: string | null;
            /** Format: int32 */
            serial_baud_rate?: number | null;
            serial_connected?: boolean | null;
            camera_opened?: boolean | null;
            /** Format: double */
            camera_fps?: number | null;
            camera_resolution?: string | null;
            camera_device?: null | components["schemas"]["CameraSelector"];
            is_running?: boolean | null;
            command_state?: null | components["schemas"]["CommandState"];
            current_command?: string | null;
            command_candidates?: components["schemas"]["CommandInfo"][] | null;
            tags?: string[] | null;
            active_profile?: string | null;
            pending_profile?: string | null;
            available_profiles?: string[] | null;
            last_input?: string | null;
            holding_buttons?: string[] | null;
            /** Format: int32 */
            pid?: number | null;
            command_display_lists?: {
                [key: string]: components["schemas"]["CommandDisplayItem"][];
            } | null;
            command_display_cache_loading?: boolean | null;
        };
        StateSnapshot: {
            revision: components["schemas"]["DecimalString"];
            serial_port: string | null;
            /** Format: int32 */
            serial_baud_rate: number;
            serial_connected: boolean;
            camera_opened: boolean;
            /** Format: double */
            camera_fps: number;
            camera_resolution: string;
            camera_device: components["schemas"]["CameraSelector"];
            is_running: boolean;
            command_state: components["schemas"]["CommandState"];
            current_command: string | null;
            command_candidates: components["schemas"]["CommandInfo"][];
            tags: string[];
            active_profile: string;
            pending_profile: string | null;
            available_profiles: string[];
            last_input: string | null;
            holding_buttons: string[];
            /** Format: int32 */
            pid: number;
            command_display_lists: {
                [key: string]: components["schemas"]["CommandDisplayItem"][];
            };
            command_display_cache_loading: boolean;
        };
        /** @enum {string} */
        StickName: "LSTICK" | "RSTICK";
        StickPosition: {
            /** Format: int32 */
            x: number;
            /** Format: int32 */
            y: number;
        };
        /** @description Common successful JSON envelope. */
        Success_DynamicConfigResult: {
            data: {
                display_path: string;
                language: components["schemas"]["DynamicLanguage"];
                loaded: boolean;
            };
        };
        /** @description Common successful JSON envelope. */
        Success_GenerateLauncherResult: {
            data: {
                profile_created: boolean;
                launcher_created: boolean;
                revision: components["schemas"]["DecimalString"];
            };
        };
        /** @description Common successful JSON envelope. */
        Success_NotificationTestResult: {
            data: {
                delivered: boolean;
            };
        };
        /** @description Common successful JSON envelope. */
        Success_OperationResult: {
            data: {
                changed: boolean;
                revision: components["schemas"]["DecimalString"];
            };
        };
        /** @description Common successful JSON envelope. */
        Success_SavedScreenshot: {
            data: {
                display_path: string;
                format: components["schemas"]["ImageFormat"];
            };
        };
        /** @description Common successful JSON envelope. */
        Success_ScriptUiActionResult: {
            data: {
                accepted: boolean;
            };
        };
        /** @description Common successful JSON envelope. */
        Success_SettingsSnapshot: {
            data: {
                /** @description Random identity shared by all snapshots from one backend process. */
                instance_id: string;
                revision: components["schemas"]["DecimalString"];
                values: components["schemas"]["SettingsReadValues"];
                pending_restart_values: components["schemas"]["SettingsReadPatchValues"];
                restart_required: string[];
                apply_failures: {
                    [key: string]: string;
                };
            };
        };
        /** @description Common successful JSON envelope. */
        Success_StateSnapshot: {
            data: {
                revision: components["schemas"]["DecimalString"];
                serial_port: string | null;
                /** Format: int32 */
                serial_baud_rate: number;
                serial_connected: boolean;
                camera_opened: boolean;
                /** Format: double */
                camera_fps: number;
                camera_resolution: string;
                camera_device: components["schemas"]["CameraSelector"];
                is_running: boolean;
                command_state: components["schemas"]["CommandState"];
                current_command: string | null;
                command_candidates: components["schemas"]["CommandInfo"][];
                tags: string[];
                active_profile: string;
                pending_profile: string | null;
                available_profiles: string[];
                last_input: string | null;
                holding_buttons: string[];
                /** Format: int32 */
                pid: number;
                command_display_lists: {
                    [key: string]: components["schemas"]["CommandDisplayItem"][];
                };
                command_display_cache_loading: boolean;
            };
        };
        /** @description Common successful JSON envelope. */
        Success_UpdateCheckResult: {
            data: {
                current_version: string;
                latest_version: string;
                update_available: boolean;
                release_url: string;
            };
        };
        /** @description Common successful JSON envelope. */
        Success_Vec_CameraDevice: {
            data: {
                selector: components["schemas"]["CameraSelector"];
                label: string;
                available: boolean;
            }[];
        };
        /** @description Common successful JSON envelope. */
        Success_Vec_SerialPort: {
            data: {
                selector: string;
                label: string;
                available: boolean;
            }[];
        };
        TouchPoint: {
            /** Format: int32 */
            x: number;
            /** Format: int32 */
            y: number;
            /** @enum {boolean} */
            pressed: true;
        };
        UiStateChange: {
            cause: components["schemas"]["StateChangeCause"];
            state: components["schemas"]["StatePatch"];
            settings: null | components["schemas"]["SettingsChange"];
        };
        UpdateCheckResult: {
            current_version: string;
            latest_version: string;
            update_available: boolean;
            release_url: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    retry_camera: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmptyRequest"];
            };
        };
        responses: {
            /** @description Camera retry applied or a no-op */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success_OperationResult"];
                };
            };
            /** @description Camera retry failure */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Camera backend failure */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    screenshot: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScreenshotRequest"];
            };
        };
        responses: {
            /** @description Saved screenshot metadata or downloaded image bytes */
            200: {
                headers: {
                    /** @description Present for attachment responses */
                    "Content-Disposition"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success_SavedScreenshot"];
                    "image/png": number[];
                    "image/jpeg": number[];
                };
            };
            /** @description No frame or incompatible UI mode */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Invalid crop, name, path, or format */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Screenshot failure */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    control_command: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommandControlRequest"];
            };
        };
        responses: {
            /** @description Command transition applied or a no-op */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success_OperationResult"];
                };
            };
            /** @description Command identity was not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Command state conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Invalid command request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Command backend failure */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    reload_commands: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmptyRequest"];
            };
        };
        responses: {
            /** @description Command generation reloaded */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success_OperationResult"];
                };
            };
            /** @description Profile switch conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Worker or cache failure */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_cameras: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Fresh camera enumeration */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success_Vec_CameraDevice"];
                };
            };
            /** @description Camera enumeration failure */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_serial_ports: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Fresh serial-port enumeration */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success_Vec_SerialPort"];
                };
            };
            /** @description Serial enumeration failure */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    control_dynamic_config: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DynamicConfigControlRequest"];
            };
        };
        responses: {
            /** @description Dynamic configuration load result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success_DynamicConfigResult"];
                };
            };
            /** @description No current dynamic file */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Invalid language, path, or content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Dynamic configuration transport failure */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    test_notification: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NotificationTestRequest"];
            };
        };
        responses: {
            /** @description Test notification delivered */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success_NotificationTestResult"];
                };
            };
            /** @description Unsupported notification channel */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Notification configuration is invalid */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Notification delivery failure */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    generate_launcher: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateLauncherRequest"];
            };
        };
        responses: {
            /** @description Profile and launcher result or downloaded Windows batch bytes */
            200: {
                headers: {
                    /** @description Present for attachment responses */
                    "Content-Disposition"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success_GenerateLauncherResult"];
                    "application/x-bat": number[];
                };
            };
            /** @description Unsupported platform or UI mode */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Invalid profile or destination */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Profile or launcher write failure */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    script_ui_action: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScriptUiAction"];
            };
        };
        responses: {
            /** @description Script UI interaction accepted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success_ScriptUiActionResult"];
                };
            };
            /** @description Stale generation or completed UI object */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Invalid dialog value or Tk interaction */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Script worker interaction failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    control_serial: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SerialControlRequest"];
            };
        };
        responses: {
            /** @description Serial transition applied or a no-op */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success_OperationResult"];
                };
            };
            /** @description Serial connection failure */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Invalid serial request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Serial backend failure */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_settings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current canonical settings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success_SettingsSnapshot"];
                };
            };
            /** @description Settings snapshot failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    patch_settings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsPatchRequest"];
            };
        };
        responses: {
            /** @description Committed settings snapshot */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success_SettingsSnapshot"];
                };
            };
            /** @description Malformed JSON */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Revision or runtime conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Invalid setting transaction */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Persistence failure */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_state: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current runtime state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success_StateSnapshot"];
                };
            };
            /** @description State snapshot failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    check_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmptyRequest"];
            };
        };
        responses: {
            /** @description Version comparison */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success_UpdateCheckResult"];
                };
            };
            /** @description Update service unavailable */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    websocket: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description WebSocket upgrade */
            101: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid WebSocket upgrade */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Host or Origin rejected */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Connection identifier exhausted */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
}
