# Generated by PokeCon from settings.json and protocol.json. Do not edit.
from collections.abc import Callable
from typing import Literal, NotRequired, TypedDict

type HandlerId = int
type CommandState = Literal["running", "paused", "stopped", "error"]
type BuiltinEvent = Literal[
    "AppStartupPost",
    "AppShutdownPre",
    "SerialConnectPost",
    "SerialDisconnectPre",
    "SerialDisconnectPost",
    "CameraOpenPost",
    "CameraClosePre",
    "CameraClosePost",
    "CommandStartPre",
    "CommandStartPost",
    "CommandStopPre",
    "CommandStopPost",
    "CommandErrorPre",
    "CommandErrorPost",
    "ScriptLoadPre",
    "ScriptLoadPost",
    "ConfigReloadPre",
    "ConfigReloadPost",
    "InputPressedPre",
    "InputReleasedPost",
    "ProfileSwitchPre",
    "ProfileSwitchPost",
]
type EventName = BuiltinEvent | str
type Callback = Callable[[], Literal[False] | None]

type Language = Literal[
    "ja",
    "en",
]
type CameraCaptureResolution = Literal[
    "640x360",
    "1280x720",
    "1920x1080",
]
type CameraFlipMode = Literal[
    "none",
    "vertical",
    "horizontal",
    "both",
]
type CameraScreenshotFormat = Literal[
    "png",
    "jpeg",
]
type SerialDataFormat = Literal[
    "default",
    "qingpi",
    "3ds",
]
type NotificationsLineMenuBehavior = Literal[
    "message",
    "noop",
]
type UiWidgetMode = Literal[
    "all",
    "outputs",
    "output_1_controller",
    "output_2_controller",
    "output_1",
    "output_2",
    "controller",
]
type UiStdoutDestination = Literal[
    "output_1",
    "output_2",
]
type UiControllerPosition = Literal[
    "top",
    "bottom",
]
type UiDialogButtonPosition = Literal[
    "bottom",
    "top",
    "both",
]
type UiDesktopCloseBehavior = Literal[
    "ask",
    "shutdown",
    "keep_backend",
]
type CommandsTagMatchMode = Literal[
    "exact",
    "partial",
    "prefix",
    "suffix",
]

class CommandInfo(TypedDict):
    name: str
    module_path: str
    class_name: str
    tags: list[str]

class CommandSeparator:
    @property
    def label(self) -> str | None: ...

type CommandSortItem = CommandInfo | CommandSeparator
type CommandSortCallback = Callable[[list[CommandInfo]], list[CommandSortItem]]
type TagMatchCallback = Callable[[str, CommandInfo], bool]

class StickXY(TypedDict):
    x: int
    y: int

class StickPolar(TypedDict):
    angle: float
    strength: float

type StickInput = StickXY | StickPolar

class TouchInput(TypedDict):
    x: int
    y: int
    pressed: NotRequired[bool]

class ControllerUpdate(TypedDict):
    a: NotRequired[bool]
    b: NotRequired[bool]
    x: NotRequired[bool]
    y: NotRequired[bool]
    l: NotRequired[bool]
    r: NotRequired[bool]
    zl: NotRequired[bool]
    zr: NotRequired[bool]
    lclick: NotRequired[bool]
    rclick: NotRequired[bool]
    plus: NotRequired[bool]
    minus: NotRequired[bool]
    home: NotRequired[bool]
    capture: NotRequired[bool]
    left_stick: NotRequired[StickInput]
    right_stick: NotRequired[StickInput]
    hat: NotRequired[
        Literal[
            "up",
            "down",
            "left",
            "right",
            "up_right",
            "up_left",
            "down_right",
            "down_left",
            "neutral",
        ]
    ]
    touch: NotRequired[TouchInput]

class InputTouchscreenArea(TypedDict):
    bottom: float
    left: float
    right: float
    top: float

class PythonScriptPackagesListItem(TypedDict):
    extras: NotRequired[list[str]]
    name: str
    version: NotRequired[str]

class CallbackSoftTimeoutError(TimeoutError):
    handler_id: HandlerId
    elapsed_ms: int
    soft_timeout_ms: int

class _OptCamera:
    capture_fps: int
    capture_resolution: CameraCaptureResolution
    device: int | str
    flip_mode: CameraFlipMode
    screenshot_format: CameraScreenshotFormat

class _OptCommands:
    tag_match_mode: CommandsTagMatchMode

class _OptConfig:
    report_ignored_profile_global_settings: bool

class _OptDynamic:
    callback_hard_timeout_ms: int
    callback_max_concurrency: int
    callback_queue_capacity: int
    callback_soft_timeout_grace_ms: int
    callback_soft_timeout_ms: int

class _OptInput:
    keyboard_enabled: bool
    left_stick_mouse_enabled: bool
    right_stick_mouse_enabled: bool
    touchscreen_area: InputTouchscreenArea

class _OptNotificationsDiscord:
    avatar_url: str
    on_script_end: bool
    on_script_start: bool
    username: str
    webhook_url: str

class _OptNotificationsWindows:
    on_script_end: bool
    on_script_start: bool

class _OptNotifications:
    discord: _OptNotificationsDiscord
    windows: _OptNotificationsWindows
    line_menu_behavior: NotificationsLineMenuBehavior

class _OptPythonScriptPackages:
    list: list[PythonScriptPackagesListItem]
    override_application_constraints: bool
    override_package_metadata_constraints: bool
    revalidate_mutable_sources: bool
    uv_config: None | str

class _OptPythonScript:
    packages: _OptPythonScriptPackages
    shutdown_timeout_ms: int
    venv: str

class _OptPython:
    script: _OptPythonScript

class _OptSerial:
    baud_rate: int
    data_format: SerialDataFormat
    port: str

class _OptShortcuts:
    button_1: str
    button_10: str
    button_2: str
    button_3: str
    button_4: str
    button_5: str
    button_6: str
    button_7: str
    button_8: str
    button_9: str

class _OptUiCamera:
    guide_visible: bool
    live_view_enabled: bool
    pixel_values_visible: bool

class _OptUiDesktop:
    close_behavior: UiDesktopCloseBehavior

class _OptUi:
    camera: _OptUiCamera
    desktop: _OptUiDesktop
    controller_position: UiControllerPosition
    dialog_button_position: UiDialogButtonPosition
    fps: int
    fps_options: list[int]
    output_split_ratio: int
    stdout_destination: UiStdoutDestination
    widget_mode: UiWidgetMode

class _OptWebrtc:
    auto_recover: bool
    recovery_probe_interval_sec: int

class _OptWebsocket:
    ping_interval_sec: int
    pong_timeout_sec: int
    reconnect_interval_sec: int
    reconnect_max_retries: int

class _Opt:
    camera: _OptCamera
    commands: _OptCommands
    config: _OptConfig
    dynamic: _OptDynamic
    input: _OptInput
    notifications: _OptNotifications
    python: _OptPython
    serial: _OptSerial
    shortcuts: _OptShortcuts
    ui: _OptUi
    webrtc: _OptWebrtc
    websocket: _OptWebsocket
    active_profile: str
    auto_reload_config: bool
    jpeg_quality: int
    language: Language
    stun_server: str

class _State:
    @property
    def serial_port(self) -> str: ...
    @property
    def serial_baud_rate(self) -> int: ...
    @property
    def serial_connected(self) -> bool: ...
    @property
    def camera_opened(self) -> bool: ...
    @property
    def camera_fps(self) -> int: ...
    @property
    def camera_resolution(self) -> str: ...
    @property
    def camera_device(self) -> int | str: ...
    @property
    def is_running(self) -> bool: ...
    @property
    def command_state(self) -> CommandState: ...
    @property
    def current_command(self) -> str: ...
    @property
    def command_candidates(self) -> list[CommandInfo]: ...
    @command_candidates.setter
    def command_candidates(self, value: list[CommandInfo]) -> None: ...
    @property
    def tags(self) -> list[str]: ...
    @tags.setter
    def tags(self, value: list[str]) -> None: ...
    @property
    def active_profile(self) -> str: ...
    @property
    def pending_profile(self) -> str | None: ...
    @property
    def available_profiles(self) -> list[str]: ...
    @property
    def last_input(self) -> str | None: ...
    @property
    def holding_buttons(self) -> list[str]: ...
    @property
    def pid(self) -> int: ...

class _Autocmd:
    def on(
        self,
        event: EventName,
        *,
        callback: Callback,
        group: str | None = None,
        priority: int = 0,
        soft_timeout_ms: int | None = None,
        soft_timeout_grace_ms: int | None = None,
        hard_timeout_ms: int | None = None,
    ) -> HandlerId: ...
    def once(
        self,
        event: EventName,
        *,
        callback: Callback,
        group: str | None = None,
        priority: int = 0,
        soft_timeout_ms: int | None = None,
        soft_timeout_grace_ms: int | None = None,
        hard_timeout_ms: int | None = None,
    ) -> HandlerId: ...
    def off(self, handler_id: HandlerId) -> None: ...
    def clear(self, target: str) -> None: ...

class _Event:
    def define(self, event: str) -> None: ...
    def emit(self, event: EventName) -> None: ...
    def list_defined(self) -> list[str]: ...

class _Profile:
    def current(self) -> str: ...
    def list(self) -> list[str]: ...
    def switch(self, name: str) -> bool: ...

class _Controller:
    def update(self, value: ControllerUpdate) -> None: ...
    def reset(self) -> None: ...

class _CommandSortOptions:
    callback: CommandSortCallback | None
    priority: int
    soft_timeout_ms: int | None
    soft_timeout_grace_ms: int | None
    hard_timeout_ms: int | None

class _CommandTagMatchOptions:
    callback: TagMatchCallback | None
    priority: int
    soft_timeout_ms: int | None
    soft_timeout_grace_ms: int | None
    hard_timeout_ms: int | None

class _Commands:
    sort: _CommandSortOptions
    tag_match: _CommandTagMatchOptions

    def separator(self, label: str | None = None) -> CommandSeparator: ...

class _Errors:
    CallbackSoftTimeoutError: type[CallbackSoftTimeoutError]

    def is_callback_soft_timeout(self, error: BaseException) -> bool: ...

opt: _Opt
state: _State
autocmd: _Autocmd
event: _Event
profile: _Profile
controller: _Controller
commands: _Commands
errors: _Errors

def source(path: str) -> None: ...
