# Generated by `nix run .#generate-contracts`; do not edit.
# fmt: off
from enum import Enum, IntEnum, IntFlag
from typing import ClassVar

from .Sender import Sender

class Button(IntFlag):
    Y = 1
    B = 2
    A = 4
    X = 8
    L = 16
    R = 32
    ZL = 64
    ZR = 128
    MINUS = 256
    PLUS = 512
    LCLICK = 1024
    RCLICK = 2048
    HOME = 4096
    CAPTURE = 8192
    SELECT = MINUS
    START = PLUS
    POWER = LCLICK
    WIRELESS = RCLICK

class Hat(IntEnum):
    TOP = 0
    TOP_RIGHT = 1
    RIGHT = 2
    BTM_RIGHT = 3
    BTM = 4
    BTM_LEFT = 5
    LEFT = 6
    TOP_LEFT = 7
    CENTER = 8

class Stick(Enum):
    LEFT = 1
    RIGHT = 2

class Direction:
    UP: ClassVar[Direction]
    RIGHT: ClassVar[Direction]
    DOWN: ClassVar[Direction]
    LEFT: ClassVar[Direction]
    UP_RIGHT: ClassVar[Direction]
    DOWN_RIGHT: ClassVar[Direction]
    DOWN_LEFT: ClassVar[Direction]
    UP_LEFT: ClassVar[Direction]
    R_UP: ClassVar[Direction]
    R_RIGHT: ClassVar[Direction]
    R_DOWN: ClassVar[Direction]
    R_LEFT: ClassVar[Direction]
    R_UP_RIGHT: ClassVar[Direction]
    R_DOWN_RIGHT: ClassVar[Direction]
    R_DOWN_LEFT: ClassVar[Direction]
    R_UP_LEFT: ClassVar[Direction]

    stick: Stick
    x: int
    y: int
    showName: str | None

    def __init__(self, stick: Stick, angle: tuple[int, int] | float, magnification: float = 1.0, isDegree: bool = True, showName: str | None = None) -> None: ...
    @property
    def name(self) -> str: ...

class Touchscreen:
    x: int
    y: int

    def __init__(self, x: int, y: int) -> None: ...
    @property
    def name(self) -> str: ...

type Buttons = Button | Hat | Direction | Touchscreen
type ButtonsList = list[Buttons]
type GamepadInput = ButtonsList | Buttons

class KeyPress:
    ser: Sender

    def __init__(self, ser: Sender) -> None: ...
    def input(self, btns: GamepadInput, ifPrint: bool = True) -> None: ...
    def inputEnd(self, btns: GamepadInput, ifPrint: bool = True, unset_hat: bool = True, unset_Touchscreen: bool = True) -> None: ...
    def hold(self, btns: GamepadInput) -> None: ...
    def holdEnd(self, btns: GamepadInput) -> None: ...
    def neutral(self) -> None: ...
    def end(self) -> None: ...
