# Generated by `nix run .#generate-contracts`; do not edit.
# fmt: off
from collections.abc import Callable

from .Sender import Sender

class McuCommand:
    def __init__(self, sync_name: str) -> None: ...
    def start(self, ser: Sender, postProcess: Callable[[], None] | None) -> None: ...
    def end(self, ser: Sender) -> None: ...
