[package]
name = "pokecon-app"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "pokecon"
path = "src/main.rs"

[features]
default = []
tauri-shell = ["dep:tauri", "pokecon-desktop/tauri-shell"]

[dependencies]
async-trait.workspace = true
axum.workspace = true
base64.workspace = true
chrono.workspace = true
clap.workspace = true
parking_lot.workspace = true
pokecon-contracts = { path = "../pokecon-contracts" }
pokecon-camera = { path = "../pokecon-camera" }
pokecon-core = { path = "../pokecon-core" }
pokecon-desktop = { path = "../pokecon-desktop" }
pokecon-device = { path = "../pokecon-device" }
pokecon-dynamic = { path = "../pokecon-dynamic" }
pokecon-server = { path = "../pokecon-server" }
pokecon-settings = { path = "../pokecon-settings" }
pokecon-worker = { path = "../pokecon-worker" }
reqwest.workspace = true
rumqttc.workspace = true
semver.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tauri = { workspace = true, optional = true }
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true
url.workspace = true

[build-dependencies]
tauri-build = { version = "2.5.4", features = [] }

[dev-dependencies]
tempfile.workspace = true

[target.'cfg(unix)'.dev-dependencies]
nix.workspace = true

[lints]
workspace = true
