[package]
name = "pokecon-app"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "pokecon"
path = "src/main.rs"

[features]
default = []
tauri-shell = ["pokecon-desktop/tauri-shell"]

[dependencies]
clap.workspace = true
parking_lot.workspace = true
pokecon-contracts = { path = "../pokecon-contracts" }
pokecon-core = { path = "../pokecon-core" }
pokecon-desktop = { path = "../pokecon-desktop" }
pokecon-device = { path = "../pokecon-device" }
pokecon-dynamic = { path = "../pokecon-dynamic" }
pokecon-server = { path = "../pokecon-server" }
pokecon-settings = { path = "../pokecon-settings" }
pokecon-worker = { path = "../pokecon-worker" }
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true

[dev-dependencies]
tempfile.workspace = true

[target.'cfg(unix)'.dev-dependencies]
nix.workspace = true

[lints]
workspace = true
