[package]
name = "pokecon-camera"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
atomic-write-file.workspace = true
chrono.workspace = true
getrandom.workspace = true
hex.workspace = true
image.workspace = true
serde.workspace = true
serde_json.workspace = true
shared_memory.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
nokhwa = { workspace = true, features = ["input-v4l"] }
v4l.workspace = true

[target.'cfg(target_os = "windows")'.dependencies]
nokhwa = { workspace = true, features = ["input-msmf"] }

[dev-dependencies]
tempfile.workspace = true

[lints.rust]
unsafe_code = "deny"
unsafe_op_in_unsafe_fn = "deny"

[lints.clippy]
all = { level = "deny", priority = -1 }
pedantic = { level = "deny", priority = -1 }
module_name_repetitions = "allow"
must_use_candidate = "allow"
