[package]
name = "pokecon-worker"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "pokecon-worker"
path = "src/main.rs"

[dependencies]
clap.workspace = true
pokecon-core = { path = "../pokecon-core" }
serde.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true

[lints]
workspace = true
