"""Classify changed repository paths into the normal-CI execution regions."""

from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import subprocess
import sys
from dataclasses import dataclass
from enum import StrEnum
from pathlib import Path, PurePosixPath
from typing import TYPE_CHECKING, Final, Never

if TYPE_CHECKING:
    from collections.abc import Iterable, Sequence


class Region(StrEnum):
    """Stable region names exported to the normal CI workflow."""

    DOCS = "docs"
    CONTRACTS = "contracts"
    RUST = "rust"
    PYTHON = "python"
    ROUTING = "routing"
    WEB = "web"
    PRODUCT = "product"
    REMOTE_FLAKE = "remote_flake"


REGIONS: Final = tuple(Region)
SCHEMA_VERSION: Final = 1
ZERO_OBJECT_IDS: Final = frozenset({"0" * 40, "0" * 64})

CI_CONTROL_PATHS: Final = frozenset(
    {
        "flake.lock",
        "flake.nix",
        "rust/pokecon/registry/ci.json",
        "scripts/ci-watch.sh",
        "tests/quality/test_ci_aggregate.py",
        "tests/quality/test_ci_regions.py",
        "tests/quality/test_ci_timing.py",
    }
)
CI_CONTROL_PREFIXES: Final = (".github/", "scripts/ci/", "scripts/quality/")

DOC_PATHS: Final = frozenset(
    {
        ".markdownlint.json",
        ".textlintrc.json",
        "LICENSE",
    }
)
CONTRACT_PATHS: Final = frozenset(
    {
        "SPECIFICATION.md",
        "rust/pokecon/src/contract_generator.rs",
        "rust/pokecon/src/openapi_generator.rs",
        "rust/pokecon/src/bin/generate_contracts.rs",
        "rust/pokecon/src/bin/generate_openapi.rs",
        "rust/pokecon/src/server/api.rs",
        "rust/pokecon/src/server/openapi.rs",
        "rust/pokecon/src/server/paths.rs",
        "rust/pokecon/tests/contract_sync.rs",
        "web/src/lib/api/openapi.json",
        "web/src/lib/api/openapi.ts",
    }
)
CONTRACT_PREFIXES: Final = (
    "api/",
    "compatibility/",
    "generated/",
    "python/pokecon/typings/",
    "rust/pokecon/registry/",
    "rust/pokecon/src/contracts/",
    "scripts/acceptance/",
    "scripts/compatibility/",
    "tests/acceptance/",
    "tests/compatibility/",
)
COMPATIBILITY_PREFIXES: Final = (
    "compatibility/",
    "scripts/compatibility/",
    "tests/compatibility/",
)
RUST_ROOT_PATHS: Final = frozenset({"Cargo.lock", "Cargo.toml", "rust-toolchain.toml"})
PYTHON_ROOT_PATHS: Final = frozenset(
    {
        "pyproject.toml",
        "pyrightconfig.json",
        "requirements.txt",
        "ruff.toml",
        "uv.lock",
    }
)
ROUTING_PATHS: Final = frozenset(
    {
        ".gitignore",
        "Cargo.lock",
        "Cargo.toml",
        "LICENSE",
        "flake.lock",
        "flake.nix",
        "pyproject.toml",
        "rust-toolchain.toml",
        "rust/pokecon/Cargo.toml",
        "rust/pokecon/build.rs",
        "rust/pokecon/icons/32x32.png",
        "rust/pokecon/icons/128x128.png",
        "rust/pokecon/icons/128x128@2x.png",
        "rust/pokecon/icons/icon.icns",
        "rust/pokecon/icons/icon.ico",
        "rust/pokecon/linux/70-pokecon-controller.rules",
        "rust/pokecon/linux/reload-udev.sh",
        "scripts/integration/virtual-io-smoke.sh",
        "scripts/release/build_runtime.py",
        "scripts/release/normalize_debian_package.py",
        "scripts/release/normalize_linux_elf.py",
        "scripts/release/stage.py",
        "tests/quality/test_ui_package_check.py",
        "uv.lock",
    }
)
ROUTING_RUST_SOURCE_PREFIX: Final = "rust/pokecon/src/"
ROUTING_ACL_PREFIXES: Final = (
    "rust/pokecon/capabilities/",
    "rust/pokecon/permissions/",
)
ROUTING_EXCLUDED_PREFIXES: Final = ("rust/pokecon/permissions/autogenerated/",)
ROUTING_TAURI_CONFIG_PARENT: Final = PurePosixPath("rust/pokecon")
ROUTING_TAURI_CONFIG_PATTERN_TEXT: Final = (
    r"(?:tauri(?:\.[^.]+)?\.conf\.(?:json|json5)|Tauri(?:\.[^.]+)?\.toml)"
)
ROUTING_TAURI_CONFIG_PATTERN: Final = re.compile(ROUTING_TAURI_CONFIG_PATTERN_TEXT)
ROUTING_CARGO_CONFIG_NAMES: Final = frozenset({"config", "config.toml"})
ROUTING_CARGO_CONFIG_EXCLUDED_PARTS: Final = frozenset(
    {
        ".git",
        ".mypy_cache",
        ".pytest_cache",
        ".ruff_cache",
        ".venv",
        ".worktree",
        "node_modules",
        "target",
    }
)
PRODUCT_ROOT_PATHS: Final = frozenset(
    {
        "Cargo.lock",
        "Cargo.toml",
        "flake.lock",
        "flake.nix",
        "pyproject.toml",
        "requirements.txt",
        "rust-toolchain.toml",
        "uv.lock",
    }
)
PRODUCT_PREFIXES: Final = (
    "python/",
    "scripts/integration/",
    "scripts/release/",
    "tests/fixtures/cli-help/",
    "web/",
)
REMOTE_FLAKE_PATHS: Final = frozenset(
    {
        "Cargo.lock",
        "Cargo.toml",
        "flake.lock",
        "flake.nix",
        "rust-toolchain.toml",
    }
)


class ClassificationError(ValueError):
    """Raised when changed-path input cannot be classified safely."""


@dataclass(frozen=True, slots=True)
class Classification:
    """Immutable region decision and its path-level evidence."""

    changed_paths: tuple[str, ...]
    applicable: frozenset[Region]
    reason_paths: tuple[tuple[Region, tuple[str, ...]], ...]
    fail_closed: bool

    @property
    def regions(self) -> dict[str, bool]:
        """Return every stable region name, including negative decisions."""
        return {region.value: region in self.applicable for region in REGIONS}

    @property
    def reasons(self) -> dict[str, list[str]]:
        """Return sorted changed paths that selected each region."""
        reasons = dict(self.reason_paths)
        return {region.value: list(reasons[region]) for region in REGIONS}

    def as_json_object(self) -> dict[str, object]:
        """Return the versioned stdout representation."""
        return {
            "schema_version": SCHEMA_VERSION,
            "changed_paths": list(self.changed_paths),
            "regions": self.regions,
            "reasons": self.reasons,
            "fail_closed": self.fail_closed,
        }


def _invalid(message: str) -> Never:
    raise ClassificationError(message)


def _under(path: str, prefixes: Iterable[str]) -> bool:
    return any(path.startswith(prefix) for prefix in prefixes)


def normalize_changed_path(raw_path: str) -> str:
    """Normalize one Git-style repository-relative path."""
    if not raw_path or "\0" in raw_path:
        _invalid("changed paths must be non-empty and must not contain NUL")
    path = PurePosixPath(raw_path)
    if path.is_absolute() or ".." in path.parts:
        _invalid(f"changed path must stay repository-relative: {raw_path!r}")
    normalized = path.as_posix()
    if normalized == ".":
        _invalid(f"changed path does not name a file: {raw_path!r}")
    return normalized


def is_ci_control_path(path: str) -> bool:
    """Return whether a path can alter CI selection or its ownership contract."""
    return path in CI_CONTROL_PATHS or _under(path, CI_CONTROL_PREFIXES)


def is_routing_path(path: str) -> bool:
    """Return whether a path is a direct production-routing audit input."""
    if path in ROUTING_PATHS:
        return True
    if path.startswith(ROUTING_RUST_SOURCE_PREFIX) and path.endswith(".rs"):
        return True
    if _under(path, ROUTING_ACL_PREFIXES) and not _under(
        path, ROUTING_EXCLUDED_PREFIXES
    ):
        return True

    candidate = PurePosixPath(path)
    if (
        candidate.parent == ROUTING_TAURI_CONFIG_PARENT
        and ROUTING_TAURI_CONFIG_PATTERN.fullmatch(candidate.name) is not None
    ):
        return True
    return (
        candidate.name in ROUTING_CARGO_CONFIG_NAMES
        and candidate.parent.name == ".cargo"
        and not ROUTING_CARGO_CONFIG_EXCLUDED_PARTS.intersection(candidate.parts)
    )


def regions_for_path(path: str) -> frozenset[Region]:
    """Return every directly affected region for one normalized path."""
    if is_ci_control_path(path):
        return frozenset(REGIONS)

    regions: set[Region] = set()
    suffix = PurePosixPath(path).suffix.lower()

    if path in DOC_PATHS or suffix in {".md", ".txt"} or _under(path, ("docs/",)):
        regions.add(Region.DOCS)

    if path in CONTRACT_PATHS or _under(path, CONTRACT_PREFIXES):
        regions.add(Region.CONTRACTS)

    if _under(path, COMPATIBILITY_PREFIXES):
        # Compatibility evidence is executed by rust-ci-core and historically
        # shared the immutable product-smoke boundary.  Treating it as only a
        # generated-contract change would silently omit both guarantees.
        regions.update((Region.RUST, Region.PRODUCT))

    if path in RUST_ROOT_PATHS or (
        _under(path, ("rust/",))
        and (suffix in {".rs", ".toml"} or PurePosixPath(path).name == "build.rs")
    ):
        regions.add(Region.RUST)

    if (
        path in PYTHON_ROOT_PATHS
        or _under(path, ("python/",))
        or suffix in {".py", ".pyi"}
    ):
        regions.add(Region.PYTHON)

    if is_routing_path(path):
        regions.add(Region.ROUTING)

    if _under(path, ("web/",)):
        regions.add(Region.WEB)

    rust_product_path = _under(path, ("rust/pokecon/",)) and not _under(
        path,
        ("rust/pokecon/tests/", "rust/pokecon/src/tests/"),
    )
    if (
        path in PRODUCT_ROOT_PATHS
        or rust_product_path
        or _under(path, PRODUCT_PREFIXES)
    ):
        regions.add(Region.PRODUCT)

    if path in REMOTE_FLAKE_PATHS:
        regions.add(Region.REMOTE_FLAKE)

    return frozenset(regions)


def classify_paths(changed_paths: Iterable[str]) -> Classification:
    """Classify explicit changed paths with sorted, duplicate-free evidence."""
    normalized_paths = tuple(
        sorted({normalize_changed_path(path) for path in changed_paths})
    )
    reasons: dict[Region, set[str]] = {region: set() for region in REGIONS}
    fail_closed = False
    for path in normalized_paths:
        if is_ci_control_path(path):
            fail_closed = True
        for region in regions_for_path(path):
            reasons[region].add(path)
    reason_paths = tuple((region, tuple(sorted(reasons[region]))) for region in REGIONS)
    applicable = frozenset(region for region in REGIONS if reasons[region])
    return Classification(
        changed_paths=normalized_paths,
        applicable=applicable,
        reason_paths=reason_paths,
        fail_closed=fail_closed,
    )


def _git_executable() -> str:
    executable = shutil.which("git")
    if executable is None:
        _invalid("git is unavailable for offline changed-path discovery")
    return executable


def _run_git(repository: Path, arguments: Sequence[str]) -> bytes:
    if not repository.is_dir():
        _invalid(f"repository directory does not exist: {repository}")
    try:
        completed = subprocess.run(  # noqa: S603 - Nix resolves the Git executable.
            [_git_executable(), "-C", str(repository), *arguments],
            check=False,
            capture_output=True,
        )
    except OSError as error:
        message = f"unable to execute git: {error}"
        raise ClassificationError(message) from error
    if completed.returncode != 0:
        detail = os.fsdecode(completed.stderr).strip() or "no diagnostic"
        _invalid(f"git {' '.join(arguments[:2])} failed: {detail}")
    return completed.stdout


def _resolve_commit(repository: Path, revision: str, label: str) -> str:
    if not revision or "\0" in revision:
        _invalid(f"{label} must be a non-empty Git revision without NUL")
    output = _run_git(
        repository,
        ("rev-parse", "--verify", "--end-of-options", f"{revision}^{{commit}}"),
    )
    commits = output.decode("ascii", errors="strict").splitlines()
    if (
        len(commits) != 1
        or not commits[0]
        or any(character not in "0123456789abcdef" for character in commits[0])
    ):
        _invalid(f"{label} did not resolve to one canonical commit")
    return commits[0]


def _decode_git_path(raw_path: bytes) -> str:
    if not raw_path:
        _invalid("git returned an empty changed path")
    return normalize_changed_path(os.fsdecode(raw_path))


def _parse_name_status(output: bytes) -> tuple[str, ...]:
    if not output:
        return ()
    if not output.endswith(b"\0"):
        _invalid("git diff name-status output was not NUL terminated")
    fields = output[:-1].split(b"\0")
    paths: list[str] = []
    index = 0
    while index < len(fields):
        try:
            status = fields[index].decode("ascii", errors="strict")
        except UnicodeDecodeError as error:
            message = "git diff returned a non-ASCII change status"
            raise ClassificationError(message) from error
        index += 1
        if not status or status[0] not in "ACDMTUXBR":
            _invalid(f"git diff returned an unsupported change status: {status!r}")
        path_count = 2 if status[0] in "CR" else 1
        if index + path_count > len(fields):
            _invalid(f"git diff omitted paths for change status {status!r}")
        paths.extend(
            _decode_git_path(fields[path_index])
            for path_index in range(index, index + path_count)
        )
        index += path_count
    return tuple(sorted(set(paths)))


def git_changed_paths(
    *,
    repository: Path,
    base: str,
    head: str,
) -> tuple[str, ...]:
    """Read changed paths from locally available Git base/head objects only."""
    head_commit = _resolve_commit(repository, head, "head")
    if base in ZERO_OBJECT_IDS:
        output = _run_git(
            repository,
            ("ls-tree", "-r", "--name-only", "-z", head_commit),
        )
        if output and not output.endswith(b"\0"):
            _invalid("git ls-tree output was not NUL terminated")
        fields = output[:-1].split(b"\0") if output else []
        return tuple(sorted({_decode_git_path(field) for field in fields}))

    base_commit = _resolve_commit(repository, base, "base")
    output = _run_git(
        repository,
        (
            "diff",
            "--name-status",
            "-z",
            "--find-renames",
            "--find-copies",
            base_commit,
            head_commit,
            "--",
        ),
    )
    return _parse_name_status(output)


def classify_git_diff(
    *,
    repository: Path,
    base: str,
    head: str,
) -> Classification:
    """Classify an offline Git base/head comparison."""
    return classify_paths(
        git_changed_paths(repository=repository, base=base, head=head)
    )


def write_github_output(path: Path, classification: Classification) -> None:
    """Append scalar region outputs and a compact region object for Actions."""
    regions_json = json.dumps(
        classification.regions,
        sort_keys=True,
        separators=(",", ":"),
    )
    lines = [
        *(
            f"{region.value}={str(region in classification.applicable).lower()}"
            for region in REGIONS
        ),
        f"regions_json={regions_json}",
    ]
    try:
        with path.open("a", encoding="utf-8", newline="\n") as output:
            output.write("\n".join(lines) + "\n")
    except OSError as error:
        message = f"unable to write GitHub output {path}: {error}"
        raise ClassificationError(message) from error


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "paths",
        nargs="*",
        help="explicit repository-relative changed paths",
    )
    parser.add_argument(
        "--path",
        action="append",
        default=[],
        dest="option_paths",
        help="explicit changed path; may be repeated",
    )
    parser.add_argument("--base", help="locally available Git base commit")
    parser.add_argument("--head", help="locally available Git head commit")
    parser.add_argument(
        "--repository",
        type=Path,
        default=Path.cwd(),
        help="Git worktree used with --base/--head",
    )
    parser.add_argument(
        "--github-output",
        type=Path,
        help="append region outputs to this GitHub Actions output file",
    )
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    """Run the changed-region classifier CLI."""
    parser = _parser()
    arguments = parser.parse_args(argv)
    explicit_paths = [*arguments.paths, *arguments.option_paths]
    base: str | None = arguments.base
    head: str | None = arguments.head
    git_mode = base is not None or head is not None
    if explicit_paths and git_mode:
        parser.error("explicit paths cannot be combined with --base/--head")
    if git_mode and (base is None or head is None):
        parser.error("--base and --head must be provided together")
    if not explicit_paths and not git_mode:
        parser.error("provide explicit changed paths or --base/--head")

    try:
        if git_mode:
            if base is None or head is None:
                parser.error("--base and --head must be provided together")
            classification = classify_git_diff(
                repository=arguments.repository,
                base=base,
                head=head,
            )
        else:
            classification = classify_paths(explicit_paths)
        if arguments.github_output is not None:
            write_github_output(arguments.github_output, classification)
    except (ClassificationError, UnicodeError) as error:
        parser.error(str(error))

    json.dump(classification.as_json_object(), sys.stdout, sort_keys=True)
    sys.stdout.write("\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
