[package]
name = "pokecon-desktop"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
build = false

[features]
default = []

[dependencies]
pokecon-core = { path = "../pokecon-core" }
opener.workspace = true
rfd.workspace = true
tauri.workspace = true
tauri-plugin-single-instance.workspace = true
thiserror.workspace = true

[dev-dependencies]
tokio.workspace = true

[lints]
workspace = true
