[package]
name = "pokecon-net"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Socket and MQTT communication for Poke-Controller"

[dependencies]
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
rumqttc = "0.24"
bytes = "1"

pokecon-events = { path = "../pokecon-events" }

[dev-dependencies]
tokio = { workspace = true, features = ["full"] }
tracing-subscriber = { workspace = true }
