[package]
name = "pokecon-dynamic"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
async-trait.workspace = true
atomic-write-file.workspace = true
parking_lot.workspace = true
pokecon-contracts = { path = "../pokecon-contracts" }
pokecon-device = { path = "../pokecon-device" }
pokecon-settings = { path = "../pokecon-settings" }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true

[dev-dependencies]
tempfile.workspace = true
tokio.workspace = true

[lints]
workspace = true
