def on(event_name: str, callback, phase=None, pattern=None, group=None): ...


def once(event_name: str, callback, phase=None, pattern=None): ...


def off(handler_id): ...


def off_all(): ...


def autocmd_group(name: str): ...


def autocmd_clear(group: str): ...


def emit(event_name: str, data): ...


def define_event(event_name: str, schema): ...
