use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write as _;

use serde_json::Value;

use crate::model::{Setting, ValueSchema};
use crate::{ContractError, PROTOCOL_REGISTRY_JSON, parse_object_registry, settings_registry};

const GENERATED_PYTHON_HEADER: &str =
    "# Generated by PokeCon from settings.json and protocol.json. Do not edit.\n";
const GENERATED_LUA_HEADER: &str =
    "-- Generated by PokeCon from settings.json and protocol.json. Do not edit.\n";

const STATE_FIELDS: &[(&str, &str, &str, bool)] = &[
    ("serial_port", "str", "string", false),
    ("serial_baud_rate", "int", "integer", false),
    ("serial_connected", "bool", "boolean", false),
    ("camera_opened", "bool", "boolean", false),
    ("camera_fps", "int", "integer", false),
    ("camera_resolution", "str", "string", false),
    ("camera_device", "int | str", "integer|string", false),
    ("is_running", "bool", "boolean", false),
    ("command_state", "CommandState", "CommandState", false),
    ("current_command", "str", "string", false),
    (
        "command_candidates",
        "list[CommandInfo]",
        "CommandInfo[]",
        true,
    ),
    ("tags", "list[str]", "string[]", true),
    ("active_profile", "str", "string", false),
    ("pending_profile", "str | None", "string|nil", false),
    ("available_profiles", "list[str]", "string[]", false),
    ("last_input", "str | None", "string|nil", false),
    ("holding_buttons", "list[str]", "string[]", false),
    ("pid", "int", "integer", false),
];

const COMMAND_MEMBERS: &[&str] = &[
    "separator",
    "sort.callback",
    "sort.priority",
    "sort.soft_timeout_ms",
    "sort.soft_timeout_grace_ms",
    "sort.hard_timeout_ms",
    "tag_match.callback",
    "tag_match.priority",
    "tag_match.soft_timeout_ms",
    "tag_match.soft_timeout_grace_ms",
    "tag_match.hard_timeout_ms",
];

/// Generates the complete Python 3.14 dynamic-configuration stub.
///
/// # Errors
///
/// Returns a contract error when a registry is invalid or its public surface
/// no longer matches the implemented typed template.
pub fn dynamic_python_typings() -> Result<String, ContractError> {
    let contract = DynamicContract::load()?;
    let settings = dynamic_settings()?;
    validate_fixed_surface(&contract)?;

    let mut source = String::from(GENERATED_PYTHON_HEADER);
    source.push_str("from collections.abc import Callable\n");
    source.push_str("from typing import Literal, NotRequired, TypedDict\n\n");
    source.push_str("type HandlerId = int\n");
    source
        .push_str("type CommandState = Literal[\"running\", \"paused\", \"stopped\", \"error\"]\n");
    render_python_literal_alias(&mut source, "BuiltinEvent", &contract.builtin_events);
    source.push_str("type EventName = BuiltinEvent | str\n");
    source.push_str("type Callback = Callable[[], Literal[False] | None]\n\n");

    for setting in &settings {
        if let ValueSchema::Enum { values, .. } = &setting.value {
            render_python_literal_alias(&mut source, &type_name(&setting.id), values);
        }
    }

    source.push_str(PYTHON_SHARED_TYPES);
    let object_definitions = object_definitions(&settings);
    for (name, schema) in &object_definitions {
        render_python_object(&mut source, name, schema);
    }
    source.push_str(PYTHON_ERROR_TYPE);

    let settings_tree = settings_tree(&settings, TypingLanguage::Python)?;
    render_python_namespace(&mut source, &settings_tree, &[]);
    render_python_public_namespaces(&mut source);
    Ok(normalize_python_spacing(&source))
}

/// Generates the complete `LuaLS` declaration for dynamic configuration.
///
/// # Errors
///
/// Returns a contract error when a registry is invalid or its public surface
/// no longer matches the implemented typed template.
pub fn dynamic_lua_typings() -> Result<String, ContractError> {
    let contract = DynamicContract::load()?;
    let settings = dynamic_settings()?;
    validate_fixed_surface(&contract)?;

    let mut source = String::from(GENERATED_LUA_HEADER);
    source.push_str("---@alias HandlerId integer\n");
    source.push_str("---@alias CommandState \"running\"|\"paused\"|\"stopped\"|\"error\"\n");
    render_lua_event_alias(&mut source, &contract.builtin_events);
    source.push_str("---@alias EventName BuiltinEvent|string\n");
    source.push_str("---@alias Callback fun(): false|nil\n\n");

    for setting in &settings {
        if let ValueSchema::Enum { values, .. } = &setting.value {
            writeln!(
                source,
                "---@alias {} {}",
                type_name(&setting.id),
                lua_literal_union(values)
            )
            .expect("writing generated text to a String cannot fail");
        }
    }
    source.push('\n');
    source.push_str(LUA_SHARED_TYPES);
    let object_definitions = object_definitions(&settings);
    for (name, schema) in &object_definitions {
        render_lua_object(&mut source, name, schema);
    }
    source.push_str(LUA_ERROR_TYPE);

    let settings_tree = settings_tree(&settings, TypingLanguage::Lua)?;
    render_lua_namespace(&mut source, &settings_tree, &[]);
    render_lua_public_namespaces(&mut source);
    Ok(source)
}

fn dynamic_settings() -> Result<Vec<Setting>, ContractError> {
    Ok(settings_registry()?
        .settings()
        .iter()
        .filter(|setting| setting.surfaces.dynamic.name.is_some())
        .cloned()
        .collect())
}

struct DynamicContract {
    builtin_events: Vec<String>,
    namespaces: BTreeSet<String>,
    members: BTreeMap<String, BTreeSet<String>>,
}

impl DynamicContract {
    fn load() -> Result<Self, ContractError> {
        let protocol = parse_object_registry("protocol", PROTOCOL_REGISTRY_JSON)?;
        let builtin_events = protocol
            .get("builtin_events")
            .and_then(Value::as_array)
            .ok_or_else(|| invariant("protocol builtin_events must be an array"))?
            .iter()
            .map(|event| {
                event
                    .get("name")
                    .and_then(Value::as_str)
                    .map(str::to_owned)
                    .ok_or_else(|| invariant("builtin event name must be a string"))
            })
            .collect::<Result<Vec<_>, _>>()?;
        let surface = protocol
            .get("public_surfaces")
            .and_then(Value::as_array)
            .ok_or_else(|| invariant("protocol public_surfaces must be an array"))?
            .iter()
            .find(|surface| surface.get("worker").and_then(Value::as_str) == Some("dynamic_config"))
            .ok_or_else(|| invariant("dynamic_config public surface is missing"))?;
        if surface.get("forbidden_namespaces") != Some(&serde_json::json!(["Commands"])) {
            return Err(invariant(
                "dynamic_config must forbid the Commands namespace",
            ));
        }
        let namespaces = string_set_at(surface, "namespaces")?;
        let members = surface
            .get("members")
            .and_then(Value::as_object)
            .ok_or_else(|| invariant("dynamic_config members must be an object"))?
            .iter()
            .map(|(namespace, values)| Ok((namespace.clone(), string_set(values)?)))
            .collect::<Result<BTreeMap<_, _>, ContractError>>()?;
        Ok(Self {
            builtin_events,
            namespaces,
            members,
        })
    }
}

fn validate_fixed_surface(contract: &DynamicContract) -> Result<(), ContractError> {
    let expected_namespaces = BTreeSet::from_iter(
        [
            "pokecon",
            "pokecon.opt",
            "pokecon.state",
            "pokecon.autocmd",
            "pokecon.event",
            "pokecon.profile",
            "pokecon.controller",
            "pokecon.commands",
            "pokecon.errors",
        ]
        .map(str::to_owned),
    );
    if contract.namespaces != expected_namespaces {
        return Err(invariant(format!(
            "dynamic namespace drift: expected {expected_namespaces:?}, found {:?}",
            contract.namespaces
        )));
    }
    require_members(contract, "pokecon", &["source"])?;
    require_members(contract, "pokecon.autocmd", &["on", "once", "off", "clear"])?;
    require_members(
        contract,
        "pokecon.event",
        &["define", "emit", "list_defined"],
    )?;
    require_members(contract, "pokecon.profile", &["current", "list", "switch"])?;
    require_members(contract, "pokecon.controller", &["update", "reset"])?;
    require_members(
        contract,
        "pokecon.errors",
        &["CallbackSoftTimeoutError", "is_callback_soft_timeout"],
    )?;
    let state = STATE_FIELDS
        .iter()
        .map(|(name, _, _, _)| *name)
        .collect::<Vec<_>>();
    require_members(contract, "pokecon.state", &state)?;
    require_members(contract, "pokecon.commands", COMMAND_MEMBERS)
}

fn require_members(
    contract: &DynamicContract,
    namespace: &str,
    expected: &[&str],
) -> Result<(), ContractError> {
    let expected = expected
        .iter()
        .map(|member| (*member).to_owned())
        .collect::<BTreeSet<_>>();
    let actual = contract
        .members
        .get(namespace)
        .ok_or_else(|| invariant(format!("public namespace {namespace} has no member list")))?;
    if actual == &expected {
        Ok(())
    } else {
        Err(invariant(format!(
            "{namespace} member drift: expected {expected:?}, found {actual:?}"
        )))
    }
}

fn string_set_at(value: &Value, key: &str) -> Result<BTreeSet<String>, ContractError> {
    value
        .get(key)
        .ok_or_else(|| invariant(format!("missing {key}")))
        .and_then(string_set)
}

fn string_set(value: &Value) -> Result<BTreeSet<String>, ContractError> {
    value
        .as_array()
        .ok_or_else(|| invariant("expected an array of strings"))?
        .iter()
        .map(|value| {
            value
                .as_str()
                .map(str::to_owned)
                .ok_or_else(|| invariant("expected a string member"))
        })
        .collect()
}

#[derive(Default)]
struct NamespaceNode {
    namespaces: BTreeMap<String, NamespaceNode>,
    values: BTreeMap<String, String>,
}

#[derive(Clone, Copy)]
enum TypingLanguage {
    Python,
    Lua,
}

fn settings_tree(
    settings: &[Setting],
    language: TypingLanguage,
) -> Result<NamespaceNode, ContractError> {
    let mut root = NamespaceNode::default();
    for setting in settings {
        let path = setting
            .surfaces
            .dynamic
            .name
            .as_deref()
            .expect("dynamic settings were filtered")
            .strip_prefix("pokecon.opt.")
            .ok_or_else(|| {
                invariant(format!(
                    "dynamic setting path must start with pokecon.opt.: {}",
                    setting.id
                ))
            })?;
        let segments = path.split('.').collect::<Vec<_>>();
        let (name, parents) = segments
            .split_last()
            .ok_or_else(|| invariant("dynamic setting path cannot be empty"))?;
        let mut node = &mut root;
        for segment in parents {
            if node.values.contains_key(*segment) {
                return Err(invariant(format!(
                    "dynamic setting path collides at {segment}"
                )));
            }
            node = node.namespaces.entry((*segment).to_owned()).or_default();
        }
        if node.namespaces.contains_key(*name)
            || node
                .values
                .insert(
                    (*name).to_owned(),
                    match language {
                        TypingLanguage::Python => setting_type(setting),
                        TypingLanguage::Lua => lua_setting_type(setting),
                    },
                )
                .is_some()
        {
            return Err(invariant(format!(
                "duplicate or colliding dynamic setting path: {path}"
            )));
        }
    }
    Ok(root)
}

fn setting_type(setting: &Setting) -> String {
    match &setting.value {
        ValueSchema::Enum { .. } | ValueSchema::Object { .. } => type_name(&setting.id),
        ValueSchema::Array { items, .. }
            if matches!(items.as_ref(), ValueSchema::Object { .. }) =>
        {
            format!("list[{}Item]", type_name(&setting.id))
        }
        schema => python_schema_type(schema, &type_name(&setting.id)),
    }
}

fn lua_setting_type(setting: &Setting) -> String {
    match &setting.value {
        ValueSchema::Enum { .. } | ValueSchema::Object { .. } => type_name(&setting.id),
        ValueSchema::Array { items, .. }
            if matches!(items.as_ref(), ValueSchema::Object { .. }) =>
        {
            format!("{}Item[]", type_name(&setting.id))
        }
        schema => lua_schema_type(schema, &type_name(&setting.id)),
    }
}

fn object_definitions(settings: &[Setting]) -> BTreeMap<String, ValueSchema> {
    let mut definitions = BTreeMap::new();
    for setting in settings {
        collect_object_definitions(&setting.value, &type_name(&setting.id), &mut definitions);
    }
    definitions
}

fn collect_object_definitions(
    schema: &ValueSchema,
    name: &str,
    definitions: &mut BTreeMap<String, ValueSchema>,
) {
    match schema {
        ValueSchema::Object { properties, .. } => {
            definitions.insert(name.to_owned(), schema.clone());
            for (property, value) in properties {
                collect_object_definitions(
                    &value.schema,
                    &format!("{name}{}", type_name(property)),
                    definitions,
                );
            }
        }
        ValueSchema::Array { items, .. } => {
            collect_object_definitions(items, &format!("{name}Item"), definitions);
        }
        ValueSchema::Union { variants } => {
            for (index, variant) in variants.iter().enumerate() {
                collect_object_definitions(
                    variant,
                    &format!("{name}Variant{}", index + 1),
                    definitions,
                );
            }
        }
        ValueSchema::Null
        | ValueSchema::Boolean
        | ValueSchema::String { .. }
        | ValueSchema::Integer { .. }
        | ValueSchema::Number { .. }
        | ValueSchema::Enum { .. } => {}
    }
}

fn render_python_literal_alias(source: &mut String, name: &str, values: &[String]) {
    writeln!(source, "type {name} = Literal[")
        .expect("writing generated text to a String cannot fail");
    for value in values {
        writeln!(
            source,
            "    {},",
            serde_json::to_string(value).expect("literal string must serialize")
        )
        .expect("writing generated text to a String cannot fail");
    }
    source.push_str("]\n");
}

fn render_python_object(source: &mut String, name: &str, schema: &ValueSchema) {
    let ValueSchema::Object { properties, .. } = schema else {
        unreachable!("object definition map contains only object schemas");
    };
    writeln!(source, "class {name}(TypedDict):")
        .expect("writing generated text to a String cannot fail");
    for (property, value) in properties {
        let nested_name = format!("{name}{}", type_name(property));
        let value_type = python_schema_type(&value.schema, &nested_name);
        if value.required {
            writeln!(source, "    {property}: {value_type}")
                .expect("writing generated text to a String cannot fail");
        } else {
            writeln!(source, "    {property}: NotRequired[{value_type}]")
                .expect("writing generated text to a String cannot fail");
        }
    }
    source.push('\n');
}

fn python_schema_type(schema: &ValueSchema, suggested_name: &str) -> String {
    match schema {
        ValueSchema::Null => "None".to_owned(),
        ValueSchema::Boolean => "bool".to_owned(),
        ValueSchema::String { .. } => "str".to_owned(),
        ValueSchema::Integer { .. } => "int".to_owned(),
        ValueSchema::Number { .. } => "float".to_owned(),
        ValueSchema::Enum { values, .. } => format!(
            "Literal[{}]",
            values
                .iter()
                .map(|value| serde_json::to_string(value).expect("literal string must serialize"))
                .collect::<Vec<_>>()
                .join(", ")
        ),
        ValueSchema::Union { variants } => variants
            .iter()
            .map(|variant| python_schema_type(variant, suggested_name))
            .collect::<Vec<_>>()
            .join(" | "),
        ValueSchema::Array { items, .. } => format!(
            "list[{}]",
            python_schema_type(items, &format!("{suggested_name}Item"))
        ),
        ValueSchema::Object { .. } => suggested_name.to_owned(),
    }
}

fn render_python_namespace(source: &mut String, node: &NamespaceNode, path: &[String]) {
    for (name, child) in &node.namespaces {
        let mut child_path = path.to_vec();
        child_path.push(name.clone());
        render_python_namespace(source, child, &child_path);
    }
    let class_name = python_namespace_name(path);
    writeln!(source, "class {class_name}:")
        .expect("writing generated text to a String cannot fail");
    for name in node.namespaces.keys() {
        let mut child_path = path.to_vec();
        child_path.push(name.clone());
        writeln!(source, "    {name}: {}", python_namespace_name(&child_path))
            .expect("writing generated text to a String cannot fail");
    }
    for (name, value_type) in &node.values {
        writeln!(source, "    {name}: {value_type}")
            .expect("writing generated text to a String cannot fail");
    }
    source.push('\n');
}

fn python_namespace_name(path: &[String]) -> String {
    format!(
        "_Opt{}",
        path.iter()
            .map(|segment| type_name(segment))
            .collect::<String>()
    )
}

fn render_python_public_namespaces(source: &mut String) {
    source.push_str("class _State:\n");
    for (name, python_type, _, writable) in STATE_FIELDS {
        writeln!(
            source,
            "    @property\n    def {name}(self) -> {python_type}: ..."
        )
        .expect("writing generated text to a String cannot fail");
        if *writable {
            writeln!(
                source,
                "    @{name}.setter\n    def {name}(self, value: {python_type}) -> None: ..."
            )
            .expect("writing generated text to a String cannot fail");
        }
    }
    source.push('\n');
    source.push_str(PYTHON_PUBLIC_NAMESPACES);
}

fn render_lua_event_alias(source: &mut String, events: &[String]) {
    source.push_str("---@alias BuiltinEvent\n");
    for event in events {
        writeln!(source, "---| {}", lua_string(event))
            .expect("writing generated text to a String cannot fail");
    }
}

fn render_lua_object(source: &mut String, name: &str, schema: &ValueSchema) {
    let ValueSchema::Object { properties, .. } = schema else {
        unreachable!("object definition map contains only object schemas");
    };
    writeln!(source, "---@class {name}").expect("writing generated text to a String cannot fail");
    for (property, value) in properties {
        let nested_name = format!("{name}{}", type_name(property));
        let value_type = lua_schema_type(&value.schema, &nested_name);
        let optional = if value.required { "" } else { "?" };
        writeln!(source, "---@field {property}{optional} {value_type}")
            .expect("writing generated text to a String cannot fail");
    }
    source.push('\n');
}

fn lua_schema_type(schema: &ValueSchema, suggested_name: &str) -> String {
    match schema {
        ValueSchema::Null => "nil".to_owned(),
        ValueSchema::Boolean => "boolean".to_owned(),
        ValueSchema::String { .. } => "string".to_owned(),
        ValueSchema::Integer { .. } => "integer".to_owned(),
        ValueSchema::Number { .. } => "number".to_owned(),
        ValueSchema::Enum { values, .. } => lua_literal_union(values),
        ValueSchema::Union { variants } => variants
            .iter()
            .map(|variant| lua_schema_type(variant, suggested_name))
            .collect::<Vec<_>>()
            .join("|"),
        ValueSchema::Array { items, .. } => {
            format!(
                "{}[]",
                lua_schema_type(items, &format!("{suggested_name}Item"))
            )
        }
        ValueSchema::Object { .. } => suggested_name.to_owned(),
    }
}

fn render_lua_namespace(source: &mut String, node: &NamespaceNode, path: &[String]) {
    for (name, child) in &node.namespaces {
        let mut child_path = path.to_vec();
        child_path.push(name.clone());
        render_lua_namespace(source, child, &child_path);
    }
    let class_name = lua_namespace_name(path);
    writeln!(source, "---@class {class_name}")
        .expect("writing generated text to a String cannot fail");
    for name in node.namespaces.keys() {
        let mut child_path = path.to_vec();
        child_path.push(name.clone());
        writeln!(
            source,
            "---@field {name} {}",
            lua_namespace_name(&child_path)
        )
        .expect("writing generated text to a String cannot fail");
    }
    for name in node.values.keys() {
        writeln!(source, "---@field {name} {}", node.values[name])
            .expect("writing generated text to a String cannot fail");
    }
    source.push('\n');
}

fn lua_namespace_name(path: &[String]) -> String {
    format!(
        "PokeconOpt{}",
        path.iter()
            .map(|segment| type_name(segment))
            .collect::<String>()
    )
}

fn render_lua_public_namespaces(source: &mut String) {
    source.push_str("---@class PokeconState\n");
    for (name, _, lua_type, _) in STATE_FIELDS {
        writeln!(source, "---@field {name} {lua_type}")
            .expect("writing generated text to a String cannot fail");
    }
    source.push('\n');
    source.push_str(LUA_PUBLIC_NAMESPACES);
}

fn lua_literal_union(values: &[String]) -> String {
    values
        .iter()
        .map(|value| lua_string(value))
        .collect::<Vec<_>>()
        .join("|")
}

fn lua_string(value: &str) -> String {
    serde_json::to_string(value).expect("literal string must serialize")
}

fn type_name(id: &str) -> String {
    id.split(['.', '_'])
        .filter(|segment| !segment.is_empty())
        .map(|segment| {
            let mut characters = segment.chars();
            characters.next().map_or_else(String::new, |first| {
                first.to_uppercase().chain(characters).collect()
            })
        })
        .collect()
}

fn invariant(message: impl Into<String>) -> ContractError {
    ContractError::Invariant(message.into())
}

fn normalize_python_spacing(source: &str) -> String {
    let mut normalized = String::with_capacity(source.len());
    let mut previous_blank = false;
    for line in source.lines() {
        let blank = line.is_empty();
        if blank && previous_blank {
            continue;
        }
        writeln!(normalized, "{line}").expect("writing generated text to a String cannot fail");
        previous_blank = blank;
    }
    normalized
}

const PYTHON_SHARED_TYPES: &str = r#"
class CommandInfo(TypedDict):
    name: str
    module_path: str
    class_name: str
    tags: list[str]


class CommandSeparator:
    @property
    def label(self) -> str | None: ...


type CommandSortItem = CommandInfo | CommandSeparator
type CommandSortCallback = Callable[[list[CommandInfo]], list[CommandSortItem]]
type TagMatchCallback = Callable[[str, CommandInfo], bool]


class StickXY(TypedDict):
    x: int
    y: int


class StickPolar(TypedDict):
    angle: float
    strength: float


type StickInput = StickXY | StickPolar


class TouchInput(TypedDict):
    x: int
    y: int
    pressed: NotRequired[bool]


class ControllerUpdate(TypedDict):
    a: NotRequired[bool]
    b: NotRequired[bool]
    x: NotRequired[bool]
    y: NotRequired[bool]
    l: NotRequired[bool]
    r: NotRequired[bool]
    zl: NotRequired[bool]
    zr: NotRequired[bool]
    lclick: NotRequired[bool]
    rclick: NotRequired[bool]
    plus: NotRequired[bool]
    minus: NotRequired[bool]
    home: NotRequired[bool]
    capture: NotRequired[bool]
    left_stick: NotRequired[StickInput]
    right_stick: NotRequired[StickInput]
    hat: NotRequired[
        Literal[
            "up",
            "down",
            "left",
            "right",
            "up_right",
            "up_left",
            "down_right",
            "down_left",
            "neutral",
        ]
    ]
    touch: NotRequired[TouchInput]


"#;

const PYTHON_ERROR_TYPE: &str = r"class CallbackSoftTimeoutError(TimeoutError):
    handler_id: HandlerId
    elapsed_ms: int
    soft_timeout_ms: int


";

const PYTHON_PUBLIC_NAMESPACES: &str = r"class _Autocmd:
    def on(
        self,
        event: EventName,
        *,
        callback: Callback,
        group: str | None = None,
        priority: int = 0,
        soft_timeout_ms: int | None = None,
        soft_timeout_grace_ms: int | None = None,
        hard_timeout_ms: int | None = None,
    ) -> HandlerId: ...
    def once(
        self,
        event: EventName,
        *,
        callback: Callback,
        group: str | None = None,
        priority: int = 0,
        soft_timeout_ms: int | None = None,
        soft_timeout_grace_ms: int | None = None,
        hard_timeout_ms: int | None = None,
    ) -> HandlerId: ...
    def off(self, handler_id: HandlerId) -> None: ...
    def clear(self, target: str) -> None: ...


class _Event:
    def define(self, event: str) -> None: ...
    def emit(self, event: EventName) -> None: ...
    def list_defined(self) -> list[str]: ...


class _Profile:
    def current(self) -> str: ...
    def list(self) -> list[str]: ...
    def switch(self, name: str) -> bool: ...


class _Controller:
    def update(self, value: ControllerUpdate) -> None: ...
    def reset(self) -> None: ...


class _CommandSortOptions:
    callback: CommandSortCallback | None
    priority: int
    soft_timeout_ms: int | None
    soft_timeout_grace_ms: int | None
    hard_timeout_ms: int | None


class _CommandTagMatchOptions:
    callback: TagMatchCallback | None
    priority: int
    soft_timeout_ms: int | None
    soft_timeout_grace_ms: int | None
    hard_timeout_ms: int | None


class _Commands:
    sort: _CommandSortOptions
    tag_match: _CommandTagMatchOptions

    def separator(self, label: str | None = None) -> CommandSeparator: ...


class _Errors:
    CallbackSoftTimeoutError: type[CallbackSoftTimeoutError]

    def is_callback_soft_timeout(self, error: BaseException) -> bool: ...


opt: _Opt
state: _State
autocmd: _Autocmd
event: _Event
profile: _Profile
controller: _Controller
commands: _Commands
errors: _Errors


def source(path: str) -> None: ...
";

const LUA_SHARED_TYPES: &str = r#"---@class CommandInfo
---@field name string
---@field module_path string
---@field class_name string
---@field tags string[]

---@class CommandSeparator
---@field label string|nil

---@alias CommandSortItem CommandInfo|CommandSeparator
---@alias CommandSortCallback fun(commands: CommandInfo[]): CommandSortItem[]
---@alias TagMatchCallback fun(selected_tag: string, command: CommandInfo): boolean

---@class StickXY
---@field x integer
---@field y integer

---@class StickPolar
---@field angle number
---@field strength number

---@alias StickInput StickXY|StickPolar

---@class TouchInput
---@field x integer
---@field y integer
---@field pressed? boolean

---@class ControllerUpdate
---@field a? boolean
---@field b? boolean
---@field x? boolean
---@field y? boolean
---@field l? boolean
---@field r? boolean
---@field zl? boolean
---@field zr? boolean
---@field lclick? boolean
---@field rclick? boolean
---@field plus? boolean
---@field minus? boolean
---@field home? boolean
---@field capture? boolean
---@field left_stick? StickInput
---@field right_stick? StickInput
---@field hat? "up"|"down"|"left"|"right"|"up_right"|"up_left"|"down_right"|"down_left"|"neutral"
---@field touch? TouchInput

"#;

const LUA_ERROR_TYPE: &str = r#"---@class CallbackSoftTimeoutError
---@field handler_id HandlerId
---@field elapsed_ms integer
---@field soft_timeout_ms integer

---@class CallbackSoftTimeoutErrorType
---@field __name "CallbackSoftTimeoutError"

"#;

const LUA_PUBLIC_NAMESPACES: &str = r"---@class AutocmdOptions
---@field callback Callback
---@field group? string
---@field priority? integer
---@field soft_timeout_ms? integer
---@field soft_timeout_grace_ms? integer
---@field hard_timeout_ms? integer

---@class PokeconAutocmd
---@field on fun(event: EventName, options: AutocmdOptions|Callback): HandlerId
---@field once fun(event: EventName, options: AutocmdOptions|Callback): HandlerId
---@field off fun(handler_id: HandlerId)
---@field clear fun(target: string)

---@class PokeconEvent
---@field define fun(event: string)
---@field emit fun(event: EventName)
---@field list_defined fun(): string[]

---@class PokeconProfile
---@field current fun(): string
---@field list fun(): string[]
---@field switch fun(name: string): boolean

---@class PokeconController
---@field update fun(value: ControllerUpdate)
---@field reset fun()

---@class CommandSortOptions
---@field callback CommandSortCallback|nil
---@field priority integer
---@field soft_timeout_ms integer|nil
---@field soft_timeout_grace_ms integer|nil
---@field hard_timeout_ms integer|nil

---@class CommandTagMatchOptions
---@field callback TagMatchCallback|nil
---@field priority integer
---@field soft_timeout_ms integer|nil
---@field soft_timeout_grace_ms integer|nil
---@field hard_timeout_ms integer|nil

---@class PokeconCommands
---@field sort CommandSortOptions
---@field tag_match CommandTagMatchOptions
---@field separator fun(label?: string): CommandSeparator

---@class PokeconErrors
---@field CallbackSoftTimeoutError CallbackSoftTimeoutErrorType
---@field is_callback_soft_timeout fun(error: any): boolean

---@class PokeconNamespace
---@field opt PokeconOpt
---@field state PokeconState
---@field autocmd PokeconAutocmd
---@field event PokeconEvent
---@field profile PokeconProfile
---@field controller PokeconController
---@field commands PokeconCommands
---@field errors PokeconErrors
---@field source fun(path: string)

---@type PokeconNamespace
pokecon = {}
";

#[cfg(test)]
mod tests {
    use super::*;

    const TRACKED_PYTHON_TYPINGS: &str =
        include_str!("../../../python/pokecon/typings/__init__.pyi");
    const TRACKED_LUA_TYPINGS: &str = include_str!("../../../generated/lua/pokecon.d.lua");

    #[test]
    fn generated_surfaces_are_deterministic_and_forbid_commands_leakage() {
        let python = dynamic_python_typings().unwrap();
        let lua = dynamic_lua_typings().unwrap();
        assert!(python.contains("class _OptPythonScriptPackages:"));
        assert!(python.contains("type BuiltinEvent = Literal["));
        assert!(python.contains("class CommandInfo(TypedDict):"));
        assert!(!python.contains("from Commands"));
        assert!(lua.contains("---@class PokeconOptPythonScriptPackages"));
        assert!(lua.contains("---@class PokeconNamespace"));
        assert!(!lua.contains("require(\"Commands\")"));
        assert_eq!(python, dynamic_python_typings().unwrap());
        assert_eq!(lua, dynamic_lua_typings().unwrap());
    }

    #[test]
    fn tracked_typings_match_the_canonical_contracts() {
        assert_eq!(dynamic_python_typings().unwrap(), TRACKED_PYTHON_TYPINGS);
        assert_eq!(dynamic_lua_typings().unwrap(), TRACKED_LUA_TYPINGS);
    }
}
