[package]
name = "pokecon-cv"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Camera capture and image processing for Poke-Controller"

[dependencies]
tokio = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

pokecon-events = { path = "../pokecon-events" }
